### ISSUE TITLE
Can we get a version that works with .Net 2.0?

### ISSUE THREAD

**Issue by fahadhaq** [XeroAPI/Xero-Net#107]
I know this is a big ask but one of my client needs to authenticate with Xero but they are at this time unable to upgrade their systems. Its a massive system. Any chance we can get a version that would work with 2.0? Or maybe get some help some where?

Thanks in advance

**Comment by ronanq** [comment]
Sorry - there is no possibility of us (Xero) being able to assist.
The source code is all here though so if you had a developer that wanted to undertake the task, I am sure it is possible.  For general questions and assistance, it is best to use our developer community: https://community.xero.com/developer/
