### ISSUE TITLE
C# sample doesn't run

### ISSUE THREAD

**Issue by seanrockster** [XeroAPI/Xero-Net#110]
Could not load type 'Xero.Api.Example.MVC.MvcApplication'.

**Comment by MJMortimer** [comment]
I can confirm it does run. 

Can you give us some more details on your issue?

**Comment by seanrockster** [comment]
Hi

Ok, well, I cloned the repo, built it (no errors), run....no joy....Could not load type 'Xero.Api.Example.MVC.MvcApplication'.

Shouldn't really be any more complicated than that?

**Comment by MJMortimer** [comment]
I'll give it a fresh clone and see if I run into the same issue

**Comment by MJMortimer** [comment]
Seems to be an issue with the default "Debug" build configuration. If you switch to the "Release" build configuration you won't have that issue

**Comment by seanrockster** [comment]
You're right, i don't have that issue anymore, just the next exception.

{"The type initializer for 'Xero.Api.Example.MVC.Helpers.XeroApiHelper' threw an exception."}
{"The system cannot find the path specified.\r\n"}

**Comment by MJMortimer** [comment]
The PartnerMVCAuthenticator uses the file XeroApiHelper.cs to set up the bits and pieces needed to communicate with Xero's API.

You will need to alter these values accordingly https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api.Example.MVC/Helpers/XeroApiHelper.cs#L25-L39

**Comment by seanrockster** [comment]
I appreciate your patience. I did see that file, unfortunately there isn't any documentation that indicates what those fields are for. Ok I can guess a little from values being assigned, so I comment out all but baseApiUrl, signedCertificatePath (path to the pfx i generated following the instructions) and clientCertificatePassword.

All I'm trying to do is this...

I setup a demo company (done)
I added an application (done)
I copy/pasted the certificate per instructions got a consumer and secret key (done i'm guessing)
Now i just want call the api and, for example, get a list of contacts. I've tried a simple rest client, no joy, tried these sample applications and cannot get any to work. 

I think i'm missing a piece to the puzzle, unfortunately its not obvious what it is.

**Comment by MJMortimer** [comment]
That's all good. What type of application have you created? A Private one?

**Comment by seanrockster** [comment]
Yes Private, i'm trying to integrate a client's website with xero for their
accounts

**Comment by MJMortimer** [comment]
You'll want to create a Public application. As far as I'm aware Private applications cannot be used for web based applications like the MVC example.

**Comment by seanrockster** [comment]
Ah. Ok well I'll try that next. First sleep my hurts. Thanks for your help!!

**Comment by MJMortimer** [comment]
When creating your Public application, make sure to add a callback domain of localhost. The example requires this so you can be redirected back to the authorize page of the example application, which then will handle the token authentication.

Using a public application, the only settings you will care about in the XeorApiHelper.cs are callbackUrl, publicAppConsumerKey, and publicAppConsumerSecret. 

Your callbackUrl will want to look something like this http://localhost:61795//Home/Authorize. (You may want to run the application to see what port number you end up with in case it's different)

The consumer key and secret just needs to have the values from your application at app.xero.com plugged in.

**Comment by MJMortimer** [comment]
If you run into any more issues, they are best directed to our community forums, https://community.xero.com/developer/

**Comment by VanNguyen88** [comment]
I have this same issue. This is due to the Build output path in "Debug" configuration is set to bin\Debug.
Changing it to bin\ will avoid the error "Could not load type 'Xero.Api.Example.MVC.MvcApplication'."

**Comment by seanrockster** [comment]
@VanNguyen88  Thanks i'll try that

**Comment by philals** [comment]
If you run into any more issues, they are best directed to our community forums, https://community.xero.com/developer/

**Comment by gordsh** [comment]
van88, your post was most helpful. "This is due to the Build output path in "Debug" configuration is set to bin\Debug. Changing it to bin\ will avoid the error "Could not load type 'Xero.Api.Example.MVC.MvcApplication'."

I almost gave up on this and you saved the day!
