### ISSUE TITLE
Renew token

### ISSUE THREAD

**Issue by hedecan** [XeroAPI/Xero-Net#111]
Hi,

I am able to connect and retrieve some datas with the partner application, however, I cannot make the token renew after 30 min and frankly, I do not know how to do that. I have spent a lot of time to find out, but no luck so far. Can anyone show me a way to renew the token once it gets expired without redirecting the end-user through the website to authorise it. 
I appreciate your time and help.

In addition, I am using the web form, however, I am able to use the MVC Authentication method in it.

**Comment by hedecan** [comment]
Does anyone know anything about this topic please?

**Comment by jmberon** [comment]
Hi hedecan,
Took this from documentation (readme file) "Examples for renewing your access tokens can be seen in the RenewToken method overrides in the PartnerAuthenticator.cs and PartnerMVCAuthenticator.cs classes." This could be your starting point.

**Comment by hedecan** [comment]
Can you give me an example of how to use this method ?

**Comment by MJMortimer** [comment]
Hi @hedecan.
Issues like this are better off raised in our community forums.
If this is still an issue can you please raise it again here as a discussion: https://community.xero.com/developer/topic/16971/
