### ISSUE TITLE
Type of CurrencyRate is inconsistent

### ISSUE THREAD

**Issue by MatthewSteeples** [XeroAPI/Xero-Net#115]
CurrencyRate is sometimes nullable and sometimes not. Ideally it should be the same across the board, but I'm not sure which is correct.

Nullable
- Invoice
- Overpayment
- Prepayment

Regular
- BankTransaction
- BankTransfer
- CreditNote
- Payment

**Comment by MatthewSteeples** [comment]
Along these lines, there are discrepancies between nullable and non-nullable types between CreditNote and Invoice too:
* Date
* DueDate
* SubTotal
* Total
* TotalTax

**Comment by philals** [comment]
Update: some fixed via https://github.com/XeroAPI/Xero-Net/pull/161

**Comment by MJMortimer** [comment]
As we're now in a strict maintenance phase for this SDK, it's unlikely that changes for this will be brought in.

**Comment by philals** [comment]
Thanks for the update Matty! :)
