### ISSUE TITLE
Invoice element TotalDiscount is not present in the .net API

### ISSUE THREAD

**Issue by konstardiy** [XeroAPI/Xero-Net#118]
Hello!
I noticed that the XML element <TotalDiscount> of <Invoice> type is not mapped in c# classes at all.
Can i extend the Invoice type with inheritance? With editing the source?  Or I better wait for an update of .net SDK?

**Comment by MatthewSteeples** [comment]
Hi @konstardiy 
If it's something you're comfortable doing you can edit the SDK yourself and send back a Pull Request. It'll then get picked up by someone at Xero and put into the next version. Failing that someone will pick it up from this list and add it soon I would think.

**Comment by konstardiy** [comment]
Thanks for your reply. I will consider making a patch for SDK about this property...
I have also a question - does API requests count limit for day and minute applied for demo accounts?

**Comment by konstardiy** [comment]
I tweaked the code a bit for debugging purposes, and noticed that totalDiscount is not returned by server ever discountRate values in LineItems was  returned by server.
Request was made to an AU Demo accoint
Here is the piece of traced response to  GET https://api.xero.com/api.xro/2.0/Invoices?unitdp=4&page=1:
 
     {
        "Type": "ACCREC",
        "InvoiceID": "0e64a623-c2a1-446a-93ed-eb897f118cbc",
        "InvoiceNumber": "ORC1027",
        "Reference": "Portal proj",
        "Payments": [],
        "CreditNotes": [],
        "Prepayments": [],
        "Overpayments": [],
        "AmountDue": 825.00,
        "AmountPaid": 0.00,
        "AmountCredited": 0.00,
        "CurrencyRate": 1.000000,
        "HasErrors": false,
        "IsDiscounted": false,
        "HasAttachments": false,
        "Contact": {
          "ContactID": "860b99a9-0958-4c8d-a98f-bb1f092b16bb",
          "Name": "DIISR - Small Business Services",
          "Addresses": [],
          "Phones": [],
          "ContactGroups": [],
          "ContactPersons": [],
          "HasValidationErrors": false
        },
        "DateString": "2015-09-29T00:00:00",
        "Date": "\/Date(1443438000000+1300)\/",
        "DueDateString": "2015-10-19T00:00:00",
        "DueDate": "\/Date(1445166000000+1300)\/",
        "BrandingThemeID": "aefae6d5-7bbe-4e2e-aadc-302cd07a0fc1",
        "Status": "AUTHORISED",
        "LineAmountTypes": "Exclusive",
        "LineItems": [
         {
            "Description": "Feedback sessions with your stakeholders",
            "UnitAmount": 150.0000,
            "TaxType": "OUTPUT",
            "TaxAmount": 75.00,
            "LineAmount": 750.00,
            "AccountCode": "200",
            "Tracking": [
              {
                "Name": "Region",
                "Option": "Eastside",
                "TrackingCategoryID": "093af706-c2aa-4d97-a4ce-2d205a017eac",
                "Options": []
              }
            ],
            "Quantity": 5.0000,
            "LineItemID": "ad4dfaa6-9705-4c58-8c39-3ee3fc3c6bbf"
          }
        ],
        "SubTotal": 750.00,
        "TotalTax": 75.00,
        "Total": 825.00,
        "UpdatedDateUTC": "\/Date(1444215367830+1300)\/",
        "CurrencyCode": "AUD"
      },

PS: Notice that discount rate was returned from server.

**Comment by MJMortimer** [comment]
This will be resolved in #144
