### ISSUE TITLE
TimesheetLine missing EarningsTypeId Property

### ISSUE THREAD

**Issue by asgadell** [XeroAPI/Xero-Net#122]
According to Xero Support, the correct field for posting a US Timesheet is EarningsTypeId and not EarningsRateId.

## Xero Network & Developer API - ticket number 2593298
Hi XXXXXX,
THe US payroll uses, EarningsTypeID and not EarningsRateID. Although the XML elements explained  under 'the Elements for TimesheetLines' shows it correctly as  EarningsTypeID  the sample XML provided has EarningsRateID and hence the confusion.  We've update our documentation to reflect the correct TimesheetLines element. Please give it a try with it and let us know.
Sorry for the the inconvenience caused.
Regards,
Krish
 

This is fine, however there is no EarningsTypeID property on the TimesheetLine Model.

**Comment by philals** [comment]
Thanks for raising an issue.

If you feel comfortable, the best way to get changes into the .NET wrapper is via a pull request. 

Fork the repo, make the changes, and send back a pull request. The changes will be released in the next version.

This type of issue looks perfect for a pull request from the community.

Thanks
Phil - API Team

**Comment by asgadell** [comment]
I have a couple of questions regarding the changes that need to be made. Is there any way to speak with someone who has a decent knowledge of the Timesheet API endpoints for both US and AU?


Thanks,

Andrew

Andrew Smith 
Software Engineer

(314) 431-0358 St. Louis
(317) 644-8990 Indianapolis
(608) 467-1999 Madison

2015 Customer Survey Score: 4.95/5.00 

2013, 2014, 2015 Inc. 5000 Fastest Growing Private Company
2013, 2014, 2015 "Best in I.T." - Small Business Monthly
2013, 2014 CRN NextGen 250 – Top 250 I.T. Consulting Firms

--

**Comment by philals** [comment]
Thanks for the reply.

The best place to start asking questions would be the community forum (https://community.xero.com/developer/topic/16971/).

There is a section for Wrapper questions and another for API endpoint questions. This is the best place to start.

Hope this help.

**Comment by philals** [comment]
Hi Andrew

This discussion been moved here: https://community.xero.com/developer/discussion/12445167

Docs have been updated recently, so I will close this issue.

Please let us know if you have any further questions.

Thanks
Phil - API Team
