### ISSUE TITLE
Crete Item as IsTrackedAsInventory

### ISSUE THREAD

**Issue by jmawebtech** [XeroAPI/Xero-Net#123]
Hi,

I am trying to create a new item as IsTrackedAsInventory and InventoryAssetAccountCode. Your item object does not have these fields. If I add them, will it work?

**Comment by MJMortimer** [comment]
HI @jmawebtech, I have been working on updating the wrapper for tracked inventory, so watch this space!

It will come complete with example tests on how to do most standard use cases :)

**Comment by MJMortimer** [comment]
@jmawebtech, TrackedInventory has been added in #124. Be sure to look at the included example tests to get an idea on how to use Tracked Inventory Items with this library to get you going quickly
