### ISSUE TITLE
I am implementing asp web forms and getting a endless loop

### ISSUE THREAD

**Issue by henzard** [XeroAPI/Xero-Net#130]
I am using the PublicAuthenticator. When var authorizeUrl = GetAuthorizeUrl(token); I should get the token and not trigger the authorizeUrl again but the systems does not create a token.

**Comment by MJMortimer** [comment]
Hey @henzard, 

If so, are you able to give us more details on the issue is?

Cheers,
Matt

**Comment by philals** [comment]
Closed as no movement
