### ISSUE TITLE
Xero Files API - Folders

### ISSUE THREAD

**Issue by justemoilouise** [XeroAPI/Xero-Net#133]
1. Folder model returns list of folders instead of list of files
2. Folders endpoint doesn't implement Update properly
   - whenever I tried to call the Update method, it keeps on returning Bad Request even though the object I'm passing (Folder Id and new name), I believe, is valid

**Comment by philals** [comment]
Thanks for raising the issue. Are you able to fix this issue via a pull request?

**Comment by justemoilouise** [comment]
Not yet. I'm still unable to get a pull request in this issue as I am working on a different project currently. I'll try to fox it as soon as I have the time.

**Comment by MJMortimer** [comment]
point 2 resloved in https://github.com/XeroAPI/Xero-Net/pull/139

**Comment by MJMortimer** [comment]
Closing this due to lack of traction. We can reopen if necessary
