### ISSUE TITLE
LineItem AccountCode

### ISSUE THREAD

**Issue by ksasha** [XeroAPI/Xero-Net#15]
I've created a list of items in Xero, with filled Sales and Purchase details, in order to rely on default account codes (tax rates) per line item for each new Invoice. So, when creating a new invoice, for each line item I set a proper ItemCode value. However, I was getting "BadRequest" error every time. It turned out that, when AccountCode was not set explicitly, default value is taken, so the actual generated XML contains the following line, for each line item

\<AccountCode i:nil="true" /\>

which causes an error. And this is due to Attribute in LineItem class.

[DataMember]
public string AccountCode { get; set; }

(default value - null - gets used). Changing previous Attribute to

[DataMember(EmitDefaultValue = false)]

fixes the issue, and new invoice gets created with appropriate tax rate. If attribute is set up as it is on purpose, please let me know.

Thank you

**Comment by mjava1** [comment]
AccountCode on LineItem.cs has [DataMember(EmitDefaultValue = false)].
