### ISSUE TITLE
EarningsRate / RateType  does not match Xero XML API (it should be FIXEDAMOUNT instead of FIXED) 

### ISSUE THREAD

**Issue by DmitryBenefitroad** [XeroAPI/Xero-Net#159]
SDK is using a different RateType for the fixed earnings compared to Xero XML ,     FIXEDAMOUNT would be a correct value.

Xero-Net/Xero.Api/Payroll/Australia/Model/Types/RateType.cs

using System.Runtime.Serialization;

namespace Xero.Api.Payroll.Australia.Model.Types
{
    [DataContract(Namespace = "")]
    public enum RateType
    {
**        [EnumMember(Value = "FIXED")]
        Fixed,**
        [EnumMember(Value = "MULTIPLE")]
        Multiple,
        [EnumMember(Value = "RATEPERUNIT")]
        RatePerUnit
    }
}

**Comment by philals** [comment]
Hi DmitryBenefitroad, are you able to fix this via a Pull Request?

**Comment by philals** [comment]
@DmitryBenefitroad we have a release coming up if you want to send a PR then that would be great.

**Comment by MJMortimer** [comment]
Fixed in #215
