### ISSUE TITLE
Callbackurl 

### ISSUE THREAD

**Issue by Mientu** [XeroAPI/Xero-Net#16]
I am trying to use call back URL. Here i am not able to see any  way to implement the call back URL. In the GetRequestToken method there is no parameter to set the call back URL. Can you please tell is there any way to implement using call back URL.

**Comment by ronanq** [comment]
This is quite an old issue and I'm not sure it is still relevant - we don't seem to have any other reporters.
If it is still causing you some problems, follow up with an example and we can look into it further.
