### ISSUE TITLE
PurchaseOrder model conains fields that cannot be mapped to JSON response correctly

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#163]
Two fields of Xero.Api.Core.Model.PurchaseOrder class: AttentionTo and Telephone cannot be mapped to JSON response because in JSON they have different names.

The way how they look like in JSON response:
```
...
      "DeliveryAttentionTo": "attention test1",
      "DeliveryPhone": "800 1234 5678",
...
```

The way how they look like in C# model class:
```
...
        [DataMember(EmitDefaultValue = false)]
        public string AttentionTo { get; set; }

        [DataMember(EmitDefaultValue = false)]
        public string Telephone { get; set; }
...
```

The proposed fix is:
```
        [DataMember(Name = "DeliveryAttentionTo", EmitDefaultValue = false)]
        public string AttentionTo { get; set; }

        [DataMember(Name = "DeliveryPhone", EmitDefaultValue = false)]
        public string Telephone { get; set; }
```

**Comment by MJMortimer** [comment]
Hey @mpbelov, 

Thanks for bringing this to our attention. We have a change it the API coming up that will resolve this, and so no changes will be needed from the wrappers point of view

Cheers,
Matt

**Comment by MJMortimer** [comment]
We have released a fix in the API that resolves this problem. No changes are needed in the wrapper for this now
