### ISSUE TITLE
Consider deleting all the samples

### ISSUE THREAD

**Issue by ben-biddington** [XeroAPI/Xero-Net#168]
They're just noise. 

Replace with checks

**Comment by MJMortimer** [comment]
Do you mean the example projects, the "tests", or both?

**Comment by ben-biddington** [comment]
The sample projects, but the tests aren't that practical either due to rate limiting

**Comment by MJMortimer** [comment]
Yeah the executable example programs probably don't provide a great deal of value but the example applications and token stores are pretty valuable to external developers when getting started
