### ISSUE TITLE
Invoice Id always is null when Create and Find invoice

### ISSUE THREAD

**Issue by TomLingWu** [XeroAPI/Xero-Net#171]
The returned invoice instances always without Id when Create a invoice, or Find any invoices.

All these invoice object actually come with "InvoiceID" member instead of "Id".

It looks like a serialization issue on:
        [DataMember(Name = "InvoiceID", EmitDefaultValue = false)]
        public Guid Id { get; set; }

**Comment by TomLingWu** [comment]
What I temporarily fixed it without change the library:

`		Invoice FixXeroInvoice(Invoice invoice)
		{
			const string dataNameOfProperty = "InvoiceID";
			try{
				var instanceType = invoice.GetType();
				var propertyInfo = instanceType.GetProperty(dataNameOfProperty);
				var value = propertyInfo.GetValue(invoice, null);
				realId = new Guid(value.ToString());
                                invoice.Id = realId;
			} catch(Exception ex){
				Log.Error("GetInvoiceIdToFixXeroApiBug got an exception" ,ex);
			}

			return invoice;
		}
`

**Comment by philals** [comment]
Hi

Are you using Mono?

**Comment by philals** [comment]
Hi Tom are you still having this issue? Can we resolve this issue?

**Comment by TomLingWu** [comment]
It's right now.
