### ISSUE TITLE
Unable to create and update Purchase Orders

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#173]
Xero-Net API doesn't support creation and update of POs yet

**Comment by MJMortimer** [comment]
Hey @mpbelov,
The wrapper as it is does support creation of purchase orders, and the updating of purchase orders will be available in the very near future. 
Cheers, 
Matt

**Comment by mpbelov** [comment]
Hi Matt,

Sorry if my message is unclear, I'm pointing to the following problem: there is an interfave IXeroCoreApi and it doesn't describe methods with the following signatures:
```
IEnumerable<PurchaseOrder> Create(IEnumerable<PurchaseOrder> items);
PurchaseOrder Create(PurchaseOrder item);
PurchaseOrder Update(PurchaseOrder item);
```
The class XeroCoreApi doens't conaint these methods as well.
