### ISSUE TITLE
Token doesn't auto-renew

### ISSUE THREAD

**Issue by MatthewSteeples** [XeroAPI/Xero-Net#175]
We're using this library in a partner application, and the token doesn't auto-renew as it does in the old wrapper. Are there plans to include this functionality?

**Comment by MJMortimer** [comment]
Hey @MatthewSteeples, is this still an issue? From what I can see the token renewal is automatic [here](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api.Example.Applications/TokenStoreAuthenticator.cs#L59-L63)

**Comment by MJMortimer** [comment]
Closing this for now as I'm not sure it's still an issue. If it is still an issue we can reopen it
