### ISSUE TITLE
Purchase Orders GET filters are not taken into account

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#180]
At least the following filters don't work for PurchaseOrdersEndpoint:
```
XeroApi.PurchaseOrders.Where("Status <> \"DRAFT\"").Find();
XeroApi.PurchaseOrders.Where("PurchaseOrderId = GUID(\"00000000-0000-0000-0000-000000000000\")").Find();
```
The specified requests return all the purchase orders of the company.
The same filters of the InvoicesEndpoint work OK.

**Comment by MJMortimer** [comment]
Hey @mpbelov,
The PurchaseOrders endpoint works a little different than our other Endpoints and does not support the open ended where clause. 

You can see some good examples on how to use PurchaseOrders with this wrapper in the example tests here https://github.com/XeroAPI/Xero-Net/blob/master/CoreTests/Integration/PurchaseOrders/Find.cs

**Comment by mpbelov** [comment]
Hi @MJMortimer, 
Thanks a lot! It works! 

Please consider adding this information into the readme file.
