### ISSUE TITLE
Purchase order POST duplicates line items

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#181]
Please try the following _repro steps_:
1. Create new PO with 1 line in Xero via web interface and submit it for approval for isntance;
2. Get it via .NET wrapper
3. Change only the status
4. Update PO via .NET wrapper:
```
var purchaseOrder = apiCore.PurchaseOrders.Find(Guid.Parse("POGUID-5afb-4dec-af1f-6ffd5c5e0211"));
purchaseOrder.Status = Xero.Api.Core.Model.Status.PurchaseOrderStatus.Authorised;
apiCore.PurchaseOrders.Update(purchaseOrder);
```

_Expected result_: the PO changed its status to Authorised, no other changes applied
_Actual result_: the PO changed its status to Authorised, **PO conatins 2 identical lines**

**Comment by mpbelov** [comment]
The following code doesn't touch lines but removes Contact information from PO (maybe something else):
```
var po = new Xero.Api.Core.Model.PurchaseOrder() {
    Id = Guid.Parse("POGUID-530e-4d8f-a7a3-3d285b218001"),
    Status = Xero.Api.Core.Model.Status.PurchaseOrderStatus.Authorised
};
apiCore.PurchaseOrders.Update(po);
```

**Comment by mpbelov** [comment]
The following code seems to be working:
```
var purchaseOrder = apiCore.PurchaseOrders.Find(Guid.Parse("POGUID-a94d-4730-b063-030cc80ee6a1"));
purchaseOrder.LineItems.Clear();
purchaseOrder.Status = Xero.Api.Core.Model.Status.PurchaseOrderStatus.Authorised;
apiCore.PurchaseOrders.Update(purchaseOrder);
```

This doesn't look as expected behaviour.

**Comment by MJMortimer** [comment]
Hey @mpbelov,

Are you able to give me the name of your application and organisation so I can take a closer look at your requests and responses to see if I can see what's going on?

Cheers,
Matt

**Comment by mpbelov** [comment]
Hi @MJMortimer,

I use a demo company "Demo Company (Global)" and private application "AM_FIles" for API testing purposes. Hope it helps.

Mike

**Comment by MJMortimer** [comment]
Thanks for bring these issues to our attention @mpbelov. It's great to see someone wanted to get Purchase Orders integrated so quickly. 

I've already worked on a fix for the duplicate lineitems issue, and it was released this morning, so you should find that the issue no longer replicable.

I also have a fix in the works for the Contact issue, and will ping you here once it has been resolved.

Is there an issue with the third case you gave? As far as I can tell, clearing the list of LineItems on the wrapper side will only cause the entire LineItems collection to not be serialized and so the collection will just remain unchanged via the API; essentially you just aren't supplying any LineItems  on the update call.

Cheers,
Matt

**Comment by mpbelov** [comment]
Hi @MJMortimer,

Thanks for the response! We've almost integrated POs but haven't released them yet due to stabilisation issues.

The original issue has been resolved - lines don't get duplicated any more. Regarding the third case - there is no issue with it, I made a wrong assumption.

Thanks,
Mike
