### ISSUE TITLE
Is it possible to apply NOT clause for PO Status filter?

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#182]
PO endpoint skips the clause specified via `.Where()` method, instead in provides `.Status()` method. How can I specify the "_all POs with Status <> DRAFT_" condition using PO GET API?

**Comment by MJMortimer** [comment]
Hey @mpbelov ,

Unfortunately there is currently no way to do that type of search in a single API call right now.
If you would like to see this implemented in the future you can visit our [uservoice page](https://xero.uservoice.com/forums/5528-xero-accounting-api) and make a topic / vote for it.

Cheers,
Matt
