### ISSUE TITLE
Cannot change PO status from Submitted to Draft

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#185]
Please try the following steps:
1. Create PO in Xero via web interface and submit it to approval
2. GET PO via Xero-Net wrapper and change it's status to Draft
3. POST PO via Xero-Net wrapper to update its status
4. Go to Xero web interface and check PO's status

Expected behaviour: PO is in Draft
Actual behaviour: PO is in Submitted

The code is this:
```
var purchaseOrder = apiCore.PurchaseOrders.Find(Guid.Parse("ed1e40a4-a846-4836-a56b-6e73d522a43f"));
purchaseOrder.Status = Xero.Api.Core.Model.Status.PurchaseOrderStatus.Draft;
apiCore.PurchaseOrders.Update(purchaseOrder);
```

There are four actions in History & Notes section:
- 4:16am - PurchaseOrder Edited - System Generated - This purchase order has been 'Edited' through the Xero API by AM_FIles
- 4:16am - PurchaseOrder Submitted - System Generated - This purchase order has been 'Submitted' through the Xero API by AM_FIles
- 4:12am - Submitted - Mikhail Belov - Purchase order PO-0017 to Carlton Functions for 1.08.
- 4:12am - Created - Mikhail Belov - Purchase order PO-0017 to Carlton Functions for 1.08.

Changing status from Submitted to Approved works OK.

**Comment by mpbelov** [comment]
Looked into the code and it seems I found the reason. The `PurchaseOrder` class contains the following description of the `Status` field:
```
[DataMember(EmitDefaultValue = false)]
public PurchaseOrderStatus Status { get; set; }
```
And Draft status is the default value for the field. I compared the class with the `Invoice` class and it annotates the Status field in another way:
```
[DataMember]
public InvoiceStatus Status { get; set; }
```
This makes serializer not to consider Draft as the default value.

However, this change didn't help. Now I get a ValidationException while trying to move Submitted PO to Draft status with the message "PurchaseOrder status change is invalid". The same approach works for Invoices, is it possible to fix this for POs as well?

**Comment by MJMortimer** [comment]
Hey @mpbelov, 

Is the status definitely not changed to draft, or is there just no history being written for that step? 

Cheers, 
Matt

**Comment by mpbelov** [comment]
@MJMortimer, the PO status definitely not changed to draft.

**Comment by MJMortimer** [comment]
@mpbelov, it's intended that Purchase Orders cannot be changed from submitted back to draft via the API

**Comment by MJMortimer** [comment]
@mpbelov, I'll make a fix for the defaulting to draft not serializing issue now
