### ISSUE TITLE
RateExceededException

### ISSUE THREAD

**Issue by jmawebtech** [XeroAPI/Xero-Net#189]
Hi,

How do you recommend I handle a RateExceededException? Do you have any retry logic?

Details Xero.Api.Infrastructure.Exceptions.RateExceededException: oauth_problem=rate%20limit%20exceeded&oauth_problem_advice=please%20wait%20before%20retrying%20the%20xero%20api at Xero.Api.Infrastructure.Http.XeroHttpClient.HandleErrors(Response response)

**Comment by MatthewSteeples** [comment]
Take a look at the RateLimiter object and where that can be used. It's disabled by default by the looks of things

**Comment by jmawebtech** [comment]
Thanks for the feedback. How do I use this object and enable it?

**Comment by jmawebtech** [comment]
Would this work?

                return new XeroCoreApi(_applicationSettings.BaseApiUrl, _applicationSettings.Authenticator as ICertificateAuthenticator,
                    _applicationSettings.Consumer, User(), new DefaultMapper(), new DefaultMapper(), new RateLimiter());

**Comment by MJMortimer** [comment]
Hey @jmawebtech. Are you still having issues getting this going or can this issue be closed?

**Comment by jmawebtech** [comment]
Please close it. My code above worked.
