### ISSUE TITLE
Validation exceptions when updating Invoices

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#198]
The behaviour is unstable, I'm not able to reproduce it 100% but it occures very often when approving invoice:
1. Create new Invoice object;
2. Specify Id, Type, LineAmountTypes and Status. Basically we need to set only Id and Status, however to make object serialized correctly we also have to specify Type and LineAmountTypes fields because they are not nullable and will be serialized anyway;
3. Call XeroCoreApi.Update(invoice).

**Expected result**: invoice got approved, no validation errors.
**Actual result**: from time to time Xero api throws validation exceptions with different messages like:
- The description field is mandatory for each line item.
- The line total 666.88 does not match the expected line total 666.93
- Discounts may not be applied to ACCPAY invoices.

I have logged exact xml Xero-Net wrapper sends to Xero api which seems to be OK:
`<?xml version="1.0" encoding="utf-8"?><Invoices xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><Invoice><InvoiceID>CORRECT-GUID-VALUE</InvoiceID><LineAmountTypes>NoTax</LineAmountTypes><Status>AUTHORISED</Status><Type>ACCPAY</Type></Invoice></Invoices>`

Could you please fix it since it's affecting more and more of our customres.

**Comment by MJMortimer** [comment]
Hey @mpbelov, it sounds like this may be an issue with the underlying API rather tahn the wrapper itself. Could you please raise the issue with our support staff [here](https://developer.xero.com/contact-xero-developer-platform-support/)
