### ISSUE TITLE
Associations?

### ISSUE THREAD

**Issue by mrrrk** [XeroAPI/Xero-Net#202]
Hi

I can't find any support in this library for this:
http://developer.xero.com/documentation/files-api/associations/

Have I missed something?

Thanks :o)

**Comment by mrrrk** [comment]
No, I'm not missing anything.  It's definitely not there - but I need it because the attachments API restricts you to 3MB.

I've started to have a go a writing the missing piece and can now see why it was left out.  The base class for an endpoint needs to accept the endpoint URL - but for _associations_ the URL is dependant on the _file ID_.  And ApiEndpointUrl has a private setter, so can't change it once instantiated.

Any ideas?

**Comment by MatthewSteeples** [comment]
Have you had a look at how Allocations work? They also have the Id in the endpoint address so you may be able to borrow from that.

**Comment by philals** [comment]
Hi @mrrrk, let us know how you get on. We more than welcome PRs, and usually release the Nuget package after each PR if someone is asking for the function.

**Comment by mrrrk** [comment]
Okey doke.  I'll have another look and see what I can come up with...

**Comment by MJMortimer** [comment]
Added in #213

**Comment by MJMortimer** [comment]
Thank you for your contributions @mrrrk!
