### ISSUE TITLE
Methods .Find(), .Post() etc clear endpoint filters after each call

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#207]
Please consider writing about this "feature" somewhere on the first page and adding appropriate comments to the methods. It's completely unobvious behavior.

For instance you have to handle more than 1 pages of invoices. You cannot just specify filters beforehand and then call .Page(++pageNum).Find() because first call resets all the filters and second and further pages may contain the same invoices again or invoices with unexpected types and statuses.

**Comment by MatthewSteeples** [comment]
We found this when using the SummarizeErrors feature - https://github.com/XeroAPI/Xero-Net/pull/200

**Comment by MJMortimer** [comment]
I've added a note about his into the Readme and created a PR - #242
