### ISSUE TITLE
Authentication issue in Public Application

### ISSUE THREAD

**Issue by Jen143** [XeroAPI/Xero-Net#208]
I have followed this codes in connecting to Xero API: 

`var user = new ApiUser { Name = Environment.MachineName };`

`var public_app_api = new XeroCoreApi("https://api.xero.com", new PublicAuthenticator("https://api.xero.com", "https://api.xero.com", "http://localhost:55050/",
                new MemoryTokenStore()),
                new Consumer("YG9CEKIJTY9NJ71TRG6DMUN0CUDFUQ", "EGILTJ5RGPKWB5LOZBKDJPVSRH2SMJ"),user,
                new DefaultMapper(), new DefaultMapper());`

`var public_contacts = public_app_api.Contacts.Find().ToList();`

But unfortunately, I've got this error: oauth_problem=permission_denied & oauth_problem_advice=The consumer was denied access to this resource.

Can someone help me why is this happening? Thank you.

**Comment by MJMortimer** [comment]
Responded on [Community](https://community.xero.com/developer/question/37360140#answer37377821)
