### ISSUE TITLE
Missing creditnotes in Invoice object

### ISSUE THREAD

**Issue by GPHMKruijssen** [XeroAPI/Xero-Net#21]
According to the API documentation an creditnotes element is passed along with an invoice. However in this version of the XeroAPI it is missing in the invoice object. The element still exists in the API Previewer. I think someone forgot this to add in the new XeroAPI since it exists in the old one.

**Comment by rowley-xero** [comment]
The CurrencyRate was added by @ezescan-rhys and @MJMortimer added the CreditNotes. Thanks.
