### ISSUE TITLE
Rate Limiter

### ISSUE THREAD

**Issue by samwood2011** [XeroAPI/Xero-Net#216]
Im using `IXeroCoreApi CoreApi()`

which has 
`return new XeroCoreApi(_applicationSettings.BaseApiUrl, _applicationSettings.Authenticator as ICertificateAuthenticator, _applicationSettings.Consumer, User(), new DefaultMapper(), new DefaultMapper(), new RateLimiter());` 

but im still getting `oauth_problem=rate%20limit%20exceeded&oauth_problem_advice=please%20wait%20before%20retrying%20the%20xero%20api
`

it seems like its ignoring the RateLimiter()

**Comment by MJMortimer** [comment]
Closing this as it sounds like you've found the issue with how you were using the RateLimiter. If this is not the case and there's still an issue we can reopen
