### ISSUE TITLE
Dot net core support 

### ISSUE THREAD

**Issue by RichardGrundy** [XeroAPI/Xero-Net#217]
Hi,

I was going to ask whether you will be supporting dotnet core now that is has been released. But instead I cloned your repo and have spent the last few days porting it in a new branch.

I have made all the main functions async too to support the HttpClient async methods.

Right now it compiles with no errors and I will need to start testing tomorrow but wondered if you want me to submit a pull request with this in? Or would you rather I fork it?

I copied the code into a new portable dll project for core which sits alongside your existing code in the same solution:

`------ Build started: Project: Xero.Api.NetCore, Configuration: Debug Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "C:\Checkouts\Xero-Net\Xero.Api.Core" --configuration Debug --no-dependencies
1>  Project Xero.Api.Core (.NETStandard,Version=v1.6) will be compiled because expected outputs are missing
1>  Compiling Xero.Api.Core for .NETStandard,Version=v1.6
1>C:\Checkouts\Xero-Net\Xero.Api.Core\Core\Endpoints\AllocationEndpoint.cs(22,43): warning CS0618: 'Allocation' is obsolete: 'Use CreditNoteAllocation'
1>C:\Checkouts\Xero-Net\Xero.Api.Core\Core\Endpoints\AllocationEndpoint.cs(22,27): warning CS0618: 'Allocation' is obsolete: 'Use CreditNoteAllocation'
1>C:\Checkouts\Xero-Net\Xero.Api.Core\Core\Endpoints\FoldersEndpoint.cs(55,44): warning CS0114: 'FoldersEndpoint.Find()' hides inherited member 'XeroReadEndpoint<FoldersEndpoint, Folder, FolderResponse>.Find()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.
1>C:\Checkouts\Xero-Net\Xero.Api.Core\Core\Endpoints\InboxEndpoint.cs(54,39): warning CS0114: 'InboxEndpoint.Find(Guid)' hides inherited member 'XeroReadEndpoint<InboxEndpoint, Folder, FolderResponse>.Find(Guid)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.
1>C:\Checkouts\Xero-Net\Xero.Api.Core\Core\Endpoints\AllocationEndpoint.cs(26,21): warning CS0618: 'Allocation' is obsolete: 'Use CreditNoteAllocation'
1>C:\Checkouts\Xero-Net\Xero.Api.Core\Infrastructure\ThirdParty\ServiceStack.Text\Json\JsonTypeSerializer.cs(564,17): warning CS0219: The variable 'withinQuotes' is assigned but its value is never used
1>C:\Checkouts\Xero-Net\Xero.Api.Core\Infrastructure\ThirdParty\ServiceStack.Text\Json\JsonTypeSerializer.cs(565,17): warning CS0219: The variable 'endsToEat' is assigned but its value is never used
1>C:\Checkouts\Xero-Net\Xero.Api.Core\Infrastructure\ThirdParty\ServiceStack.Text\DynamicProxy.cs(14,33): warning CS0649: Field 'DynamicProxy.ModuleBuilder' is never assigned to, and will always have its default value null
1>C:\Checkouts\Xero-Net\Xero.Api.Core\Infrastructure\ThirdParty\ServiceStack.Text\DynamicProxy.cs(15,35): warning CS0649: Field 'DynamicProxy.DynamicAssembly' is never assigned to, and will always have its default value null
1>  Compilation succeeded.
1>      9 Warning(s)
1>      0 Error(s)
1>  Time elapsed 00:00:02.6314132
1>
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
`

Regards

Richard

**Comment by MatthewSteeples** [comment]
_Disclaimer: Just an observer, not a Xero member_

Liking the sound of async support. When you say you've copied it into a new project, do you mean an actual copy or have you managed to make use of the "link file" functionality so that there's only one copy of the source to maintain?

**Comment by RichardGrundy** [comment]
Hi Matthew,

Unfortunately as I needed to change a lot of the  bundled third party reflection code I currently have a separate copy rather than a link. The async updates could still be used in the full version without much modification though.

Happy to discuss with the owners of the code on how they would like to proceed.

Richard

**Comment by Adz0rd** [comment]
+1

Also interested in this.

**Comment by BTXAndy** [comment]
Hi Richard, 

Great job. Could you create a fork at all? 

Thanks.

**Comment by TrplM** [comment]
> Great job. Could you create a fork at all?

Very interested in this. Would be really keen on a fork as well

**Comment by TrplM** [comment]
@RichardGrundy 

Hi there

Would appreciate a fork of this. I am busy integrating the XeroApi in to a dotnet core project and don't want to start porting the api from scratch.

Looking forward to your response.

**Comment by MJMortimer** [comment]
Hey @RichardGrundy, what is the current state that your workings are in? Do you think it would be possible to eventually have it merged back into this repo or do you think it would be too messy and breaking for other users that don't require dotnet core support?

**Comment by PaulStovell** [comment]
We'd love to see .NET core support for this library

**Comment by ctolkien** [comment]
Also chiming in for NetStandard support.

**Comment by jigarmistri** [comment]
We have also Converted Xero dot net 4.5 API code to dot net core (as there is no source code available having Xero with dot net core :-( ) and currently its working fine for converted few APIs with private key/public/partner application mode, 

**Challenges** 
The main challenge of converting application in to dot net core was Microsoft reflection library, Security Cryptography and some missing method from Microsoft basic library dll, Also after fixing build issues, we got cross platform issues like working fine with windows but received error when we deploy it on linux, so we need to remove dependency of RSAServiceprovider class as its giving "operation was not supported" while initializing RSAServiceprovider constructor from xero api and implemented custom RSASHA1 algoridhm for private application authentication. 

Also the current Xero Api has used their custom JSON conversation serialization logic , So we have used Newtonsoft json based JSON serialization, which help us to reduce number of lines code from xero api library.

The following thread will be helpful if you want to convert this library to dot net core based api
https://stackify.com/15-lessons-learned-while-converting-from-asp-net-to-net-core/

Also I'd like to have separate repository for the **Xero.Net.Core** as most of application are only supporting dot net core based libraries like Amazon Lamda, where its impossible to use .Net 4.5 based Xero library, and also when we ask xero support team for the same then they are saying  that, they are not providing support for the code related issues.  

Thanks!

**Comment by PaulStovell** [comment]
I was hoping that .NET Standard 2.0 shipping would help this library to work, but that doesn't seem to be the case - it seems this library uses Service Stack, which then uses some LINQ to SQL classes that haven't been ported to .NET Core yet (System.Data.Linq assembly). 

I switched over to:
https://github.com/visualeyes/Xero-NetStandard

Aside from some methods changing from sync to async, and from having to implement an IAuthenticator, there were no other changes necessary. It works great. 

Xero, would love to see you take on .NET Standard support.

**Comment by markogrady** [comment]
I have started to use Xero-NetStandard. It works really well. Is it worth contributing to it? or will you port this repo to .net Standard?

**Comment by MJMortimer** [comment]
Hey everyone.

I've been putting some work recently into porting the library in it's entirety to netstandard2.0 with example console applications and test projects to netcoreapp2.0.

You can find my work in a [branch on my fork](https://github.com/MJMortimer/Xero-Net/tree/netstandard).

It's probably not ready for general consumption yet, but I've had some quick tests of portability by running the example console applications as well as the example MVC application on an Ubuntu AWS EC2 machine with no trouble using DotNet Core 2.0.

The projects inside the solution have been changed to the new visual studio 2017 version of csprojs.
The SDK still runs synchronously, but I'm currently in the process of changing it to work asynchronously.

Due to this being a major change, I intend on including some other various quality of life changes that would be considered breaking changes, most of these would be pretty minor however. 

Once this work has been completed I then intend on maintaining both versions of the SDK for some length of time before merging the new version back into this main repository with a major version bump in release.

If there is any feedback, I would be happy to hear it.

**Comment by MJMortimer** [comment]
Hi all,

I've recently moved my work into our new repository and created an initial release which can be found [here](https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v0.0.1)

There is also a new nuget package for this version of the SDK which can be found [here](https://www.nuget.org/packages/Xero.Api.SDK.Core/0.0.1)

I'm yet to update the Readme for the new repository, and so some of the information there will be out of date and not relevant, but hopefully the release notes and the runnable examples will be enough to get you going.

If anyone finds any issues working with our new netstandard version of the SDK, please don't hesitate to open issues against the new repository.

**Comment by MJMortimer** [comment]
I'm going to close this issue now that the other repository has been set up. Any further discussion can take place there
