### ISSUE TITLE
Item missing UpdatedDateUtc property

### ISSUE THREAD

**Issue by sevensykoseven** [XeroAPI/Xero-Net#219]
The Item class appears to be missing an UpdatedDateUtc property.  I can query on the value and it works, like this:

var items = api.Items.Where(string.Format("UpdatedDateUTC >= DateTime.Parse(\"{0}\")", date1.ToString("yyyy-MM-dd H:mm:ss"))).And(string.Format("UpdatedDateUTC <= DateTime.Parse(\"{0}\")", date2.ToString("yyyy-MM-dd H:mm:ss"))).And("IsPurchased == true").OrderBy("Name").Find().ToList();

However the API does not have such a property.  There is an UpdatedDateUtc here:  item.PurchaseDetails.UpdatedDateUTC, but it is always null.

Can a UpdatedDateUTC property to be added to the Item class in the API?

**Comment by philals** [comment]
Hi,

Thanks for raising an issue. Are you able to send a PR with this change?

Thanks

**Comment by MJMortimer** [comment]
PR created here #243
