### ISSUE TITLE
EarningLine.EarningsRateCalculation should be EarningLine.CalculationType

### ISSUE THREAD

**Issue by JustABearOz** [XeroAPI/Xero-Net#221]
As per the Xero API documentation, EarningLine has a required property CalculationType and no property called EarningsRateCalculation.

Rename EarningLine.EarningsRateCalculation to CalculationType

**Comment by philals** [comment]
Thanks for raising an issue. The best way to fix this would be a pull request, then the whole community benefits. 

Let me know if you have issues sending a PR and I'll try give you a hand.

**Comment by adamhanniganGamesDeveloper** [comment]
What is the status on the issue? 

I notice is has been solved but has not been accepted yet.

**Comment by MJMortimer** [comment]
This will be merged with #244
