### ISSUE TITLE
C# repeating invoices

### ISSUE THREAD

**Issue by erportico** [XeroAPI/Xero-Net#230]
HI guys
I've already read this link [http://developer.xero.com/documentation/api/repeating-invoices/
](http://developer.xero.com/documentation/api/repeating-invoices/)
I'm using the wrapper for C# and I can't find a way to send repeating invoices. Is there a change to have it on the wrapper?

Thanks in advance

**Comment by MJMortimer** [comment]
Hi @erportico,

I'm not sure I understand what you are asking. 
Did you want to be able to create repeating invoices? If so, Xero's API currently does not support the creating of repeating invoices. We have an open [uservoice thread](https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/2257421-repeating-invoices-via-the-api) which you can vote for.

If that is not what you meant, can you please give some more details?

**Comment by MJMortimer** [comment]
Closing this due to lack of context.

@erportico, you can open a new issue with more information if needed
