### ISSUE TITLE
NuGet out of date

### ISSUE THREAD

**Issue by chappoo** [XeroAPI/Xero-Net#232]
Hi Xero, can we get a new version of the API published to NuGet please?  Latest is several commits behind master and has some required fixes.

https://www.nuget.org/packages/Xero.API.SDK.Minimal/

Many thanks

**Comment by MJMortimer** [comment]
Aah, sorry about that @chappoo, I'll get it pushed now

**Comment by MJMortimer** [comment]
Should be good to go!

**Comment by chappoo** [comment]
Great, thank you!
