### ISSUE TITLE
api v2.2.0 missing ICertificateAuthenticator 

### ISSUE THREAD

**Issue by manhao-chen** [XeroAPI/Xero-Net#237]
hi all, 

just updated to 2.2.0 from 2.1.10.1

what happened to the ICertificateAuthenticator object, its missing from the Xero.Api.Infrastructure.Interfaces

**Comment by MJMortimer** [comment]
Please see the Xero-Net section of the link attached to the release version. It will explain the removal of that interface among some other changes
