### ISSUE TITLE
Payment terms DAYSAFTERBILLMONTH not converted correctly

### ISSUE THREAD

**Issue by scan2invoice** [XeroAPI/Xero-Net#25]
When I set the default bill payment terms for a contact in Xero e.g. to 20 days after the end of the bill month, the .Net wrapper does not seem to translate the payment terms correctly. In my application I receive PaymentTermType FollowingMonth, but I expect AfterInvoiceMonth. 

I had a look at the online API previewer and the payment terms returnd for my example contact is "DAYSAFTERBILLMONTH", but the corresponding enum is called "DAYSAFTERINVOICEMONTH" in PaymentTermType.cs.

**Comment by MJMortimer** [comment]
Both were added to #53
