### ISSUE TITLE
Get EndPoint with Complex Condition

### ISSUE THREAD

**Issue by cgerzi** [XeroAPI/Xero-Net#250]
Hi,

I'm trying to get all invoices that fulfill 2 requirements:
1. Amount !=0
2. Status == Authorised

(For simplicity I'm just taking the 1st page, though I am aware that I'll need to loop through all pages.)

private static readonly string Invoice_Is_Authorised = String.Format("Status == \"{0}\"",
            InvoiceStatus.Authorised);
  IEnumerable<Invoice> bunchOfInvoices;
      
 bunchOfInvoices = xeroApi.Invoices.Page(1).Find().ToList(); //returns 90 invoices
 bunchOfInvoices = xeroApi.Invoices.Where(Invoice_Is_Authorised).Page(1).Find().ToList(); //returns 53 invoices     
 bunchOfInvoices = xeroApi.Invoices.Where("AmountDue != 0").Page(1).Find().ToList(); //returns 53 invoices

The above all work as expected, however when I make the query slightly more complex, these don't work:

bunchOfInvoices = xeroApi.Invoices.Where(Invoice_Is_Authorised + " && AmountDue != 0" ).Page(1).Find().ToList(); //returns 0 invoices
bunchOfInvoices = xeroApi.Invoices.Where("AmountDue != 0").And(Invoice_Is_Authorised).Page(1).Find().ToList(); //returns 0 invoices

Any help is much appreciated. Thank you!

**Comment by MJMortimer** [comment]
Hey @cgerzi, are you still finding this an issue, or have you been able to resolve it?

**Comment by cgerzi** [comment]
Hi @MJMortimer,
I'm using a workaround: I get all the Authorised invoices and do the "Amount!=0" filtering with my own code. It obviously takes longer to run since I need to first get all of the Authorised invoices.
If you have a better solution, please share.
Thanks!

**Comment by MJMortimer** [comment]
I think your work around is fine for now. I'm going to close this issue. If this becomes an issue again in the future, feel free to reopen/open a new issue
