### ISSUE TITLE
Get EndPoint with 'Where' on a Nested Property

### ISSUE THREAD

**Issue by cgerzi** [XeroAPI/Xero-Net#251]
Hi,

I'd like to get all contacts based on their invoice branding theme.
However, the following throws "No property or field 'Name' exists in type 'BrandingTheme'".
I am aware that I can get all the contacts and then filter them out on my own based on the BrandingTheme.Name, however I wanted to know if there is a better way that would only return what I need from Xero.

IEnumerable<Contact> bunchOfContacts;
bunchOfContacts = xeroApi.Contacts.Where("BrandingTheme.Name == \"Special projects\"").Page(1).Find().ToList(); 

Thanks in advance for any help!

**Comment by MJMortimer** [comment]
Unfortunately the Xero's API does not support using a where clause on nested items and so there is nothing we can do from the SDKs point of view.  Your work around you mentioned is probably the only option at this time
