### ISSUE TITLE
OAuth Error: Failed to validate signature

### ISSUE THREAD

**Issue by zzzaJ** [XeroAPI/Xero-Net#253]
I am attempting to get information using the API to populate a database. However when I run my code the following presents an error.

`XeroCoreApi private_app_api = new XeroCoreApi("https://api.xero.com/******/***/", new PrivateAuthenticator(@"C:\****\****\****\public_privatekey.pfx", "****"),
new Consumer("*************************", "**********************"), null,
new DefaultMapper(), new DefaultMapper());`

            var accounts = private_app_api.Accounts.Find().ToList();

Error Message: An unhandled exception of type 'Xero.Api.Infrastructure.Exceptions.UnauthorizedException' occurred in Xero.Api.dll

Additional information: oauth_problem=signature_invalid&oauth_problem_advice=Failed%20to%20validate%20signature

**Comment by MJMortimer** [comment]
Hey @zzzaJ, is this still an issue for you?

If it is can you please make sure that the public_privatekey.pfx is the correct one for the publickey.cer that you uploaded into app.xero.com

**Comment by zzzaJ** [comment]
Hi @MJMortimer 
No, my apologies for not closing the issue, however I did manage to solve the Xero problem.
