### ISSUE TITLE
api.Organisation - Specific method not supported

### ISSUE THREAD

**Issue by tqrecords** [XeroAPI/Xero-Net#254]
I'm using the latest version of the api and when I try to access the Organisation endpoint I get the error: 

    `var api = CoreApi();`
    `Specific method not supported`

I'm using Partner MVC Authentication.

**Comment by MJMortimer** [comment]
Hey @tqrecords, Are you able to give anymore info on this? 
A stack trace would be handy

**Comment by MJMortimer** [comment]
Are you still encountering this issue @tqrecords?

**Comment by tqrecords** [comment]
Hey, the issue can be closed. Looks like it was fixed after updating to the new version.
