### ISSUE TITLE
The element 'StatusAttributeString' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name. 

### ISSUE THREAD

**Issue by jmawebtech** [XeroAPI/Xero-Net#257]
Hi,

What does this error mean? Here is my code:

`        private void ExecuteBatch()
        {
            if(m_PurchaseOrders.Count() > 0)
            {
                m_Api.PurchaseOrders.SummarizeErrors(false);
                List<PurchaseOrder> purchaseOrders = m_Api.Create(m_PurchaseOrders).ToList();

                if (purchaseOrders.Any()) // check for invoices
                {
                    foreach (PurchaseOrder purchaseOrder in purchaseOrders)
                    {
                        //Check For any Errors
                        if (purchaseOrder.Errors != null)
                        {
                            foreach (ValidationError error in purchaseOrder.Errors)
                            {
                                if (error.Message == "Purchase Order # must be unique.")
                                {
                                    m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("PO {0} dated {1} already exists under {2}", purchaseOrder.Number, ObjectConverter.DateTimeConverter(purchaseOrder.Date).ToShortDateString(), purchaseOrder.Contact.Name)));
                                }
                                else
                                {
                                    m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, String.Format("{0}: {1}", purchaseOrder.Number, error.Message), purchaseOrder.Number));
                                }
                            }
                        }
                        else
                        {
                            m_SyncedPurchaseOrders.AddRange(purchaseOrders);
                            m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Invoice {0} under {1} placed on {2} was created successfully!", purchaseOrder.Number, purchaseOrder.Contact.Name, purchaseOrder.Date.Value), purchaseOrder.Number));
                        }
                    }
                }

            }

            if (m_Items.Count() > 0)
            {
                try
                {
                    List<Item> items = m_Api.Create(m_Items).ToList();

                    m_SyncedItems.AddRange(items);

                    foreach (Item it in items)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Item {0} was created successfully!", it.Code)));
                    }
                }
                catch (ValidationException vex)
                {
                    foreach (ValidationError error in vex.ValidationErrors)
                    {
                        if (error.Message == "Inventory Item with 'Code' provided is already in use.")
                            continue;

                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, error.Message));
                    }
                }
            }

            if (m_Invoices.Count() > 0)
            {
                m_Api.Invoices.SummarizeErrors(false);
                List<Invoice> invoices = m_Api.Create(m_Invoices).ToList();

                if (invoices.Any()) // check for invoices
                {
                    foreach (Invoice inv in invoices)
                    {
                        //Check For any Errors
                        if (inv.Errors != null)
                        {
                            foreach (ValidationError error in inv.Errors)
                            {
                                if (error.Message == "Invoice # must be unique.")
                                {
                                    m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Invoice {0} dated {1} already exists under {2}", inv.Number, ObjectConverter.DateTimeConverter(inv.Date).ToShortDateString(), inv.Contact.Name)));
                                }
                                else
                                {
                                    m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, String.Format("{0}: {1}", inv.Number, error.Message), inv.Number));
                                }
                            }
                        }
                        else
                        {
                            m_SyncedInvoices.AddRange(invoices);
                            m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Invoice {0} under {1} placed on {2} was created successfully!", inv.Number, inv.Contact.Name, inv.Date.Value), inv.Number));
                        }
                    }
                }
            }

            if (m_CreditNotes.Count() > 0)
            {
                m_Api.CreditNotes.SummarizeErrors(false);
                List<CreditNote> creditNotes = m_Api.Create(m_CreditNotes).ToList();

                if (creditNotes.Any()) // check for invoices
                {
                    foreach (CreditNote creditNote in creditNotes)
                    {
                        //Check For any Errors
                        if (creditNote.Errors != null)
                        {
                            foreach (ValidationError error in creditNote.Errors)
                            {
                                if (error.Message == "Credit Note # must be unique.")
                                {
                                    m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Credit note {0} dated {1} already exists under {2}", creditNote.Number, ObjectConverter.DateTimeConverter(creditNote.Date).ToShortDateString(), creditNote.Contact.Name)));
                                }
                                else
                                {
                                    m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, String.Format("{0}: {1}", creditNote.Number, error.Message), creditNote.Number));
                                }
                            }
                        }
                        else
                        {
                            if (m_Settings.MakeCashRefund)
                            {
                                Payment payment = CreateCashRefund(creditNote);
                                m_CashRefundPayments.Add(payment);
                            }

                            m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Credit Note {0} under {1} placed on {2} was created successfully!", creditNote.Number, creditNote.Contact.Name, creditNote.Date), creditNote.Number));
                        }
                    }
                }
            }

            if (m_CashRefundPayments.Count() > 0)
            {
                try
                {
                    m_Api.Payments.SummarizeErrors(false);
                    List<Payment> payments = m_Api.Payments.Create(m_CashRefundPayments).ToList();

                    if (payments.Any()) // check for invoices
                    {
                        foreach (Payment payment in payments)
                        {
                            //Check For any Errors
                            if (payment.Errors != null)
                            {
                                foreach (ValidationError error in payment.Errors)
                                {
                                    m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, String.Format("Payment {0}: {1}", payment.Reference, error.Message), payment.Reference));
                                }
                            }
                            else
                            {
                                m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Cash Refund {0} under {1} placed on {2} was updated successfully!", payment.CreditNote.Number, payment.CreditNote.Contact.Name, payment.Date)));
                            }
                        }
                    }
                }
                catch (ValidationException vex)
                {
                    foreach (ValidationError error in vex.ValidationErrors)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, error.Message));
                    }
                }
            }

            if (m_UpdatedCreditNotes.Count() > 0)
            {
                try
                {
                    List<CreditNote> creditNotes = m_Api.CreditNotes.Update(m_UpdatedCreditNotes).ToList();

                    foreach (CreditNote creditNote in creditNotes)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Credit Note {0} under {1} placed on {2} was created successfully!", creditNote.Number, creditNote.Contact.Name, creditNote.Date)));
                    }
                }
                catch (ValidationException vex)
                {
                    foreach (ValidationError error in vex.ValidationErrors)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, error.Message));
                    }
                }
            }

            if (m_UpdatedInvoices.Count() > 0)
            {
                try
                {
                    List<Invoice> invoices = m_Api.Invoices.Update(m_UpdatedInvoices).ToList();

                    m_SyncedInvoices.AddRange(invoices);

                    foreach (Invoice inv in invoices)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Invoice {0} under {1} placed on {2} was created successfully!", inv.Number, inv.Contact.Name, inv.Date.Value)));
                    }
                }
                catch (NullReferenceException)
                {

                }
                catch (ValidationException vex)
                {
                    foreach (ValidationError error in vex.ValidationErrors)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, error.Message));
                    }
                }
            }

            if (m_Payments.Count() > 0)
            {
                try
                {
                    List<Payment> payments = m_Api.Create(m_Payments).ToList();

                    foreach (Payment payment in payments)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Payment {0} under {1} placed on {2} was created successfully!", payment.Invoice.Number, payment.Invoice.Contact.Name, payment.Date)));
                    }
                }
                catch (ValidationException vex)
                {
                    foreach (ValidationError error in vex.ValidationErrors)
                    {
                        if ((error.Message == "Payments can only be made against Authorised documents"
                            || error.Message == "Payment amount exceeds the amount outstanding on this document") && m_Settings.InvoiceStatus == "Authorised")
                            continue;

                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, error.Message));
                    }
                }
            }

            if (m_UpdatedPayments.Count() > 0)
            {
                try
                {
                    List<Payment> payments = m_Api.Payments.Update(m_UpdatedPayments).ToList();

                    foreach (Payment payment in payments)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Payment {0} under {1} placed on {2} was updated successfully!", payment.Invoice.Number, payment.Invoice.Contact.Name, payment.Date)));
                    }
                }
                catch (ValidationException vex)
                {
                    foreach (ValidationError error in vex.ValidationErrors)
                    {
                        m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, error.Message));
                    }
                }
            }

            m_Items = new List<Item>();
            m_Invoices = new List<Invoice>();
            m_Payments = new List<Payment>();
            m_CashRefundPayments = new List<Payment>();
            m_PurchaseOrders = new List<PurchaseOrder>();
            m_LogProvider.WriteErrorMessagesToLog(m_ErrorMessages);
            m_ErrorMessages = new List<ErrorMessage>();

        }
`

Here is the stack trace:

`Error syncing orders to from Connex to Xero. Please contact JMA for assistance. Last Download 2/20/2017 2:47:15 PM Last Download End 2/21/2017 2:47:15 PM Details Xero.Api.Infrastructure.Exceptions.BadRequestException: The element 'StatusAttributeString' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name. at Xero.Api.Infrastructure.Http.XeroHttpClient.HandleErrors(Response response) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Infrastructure\Http\XeroHttpClient.cs:line 115 at Xero.Api.Infrastructure.Http.XeroHttpClient.Read[TResult,TResponse](Response response) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Infrastructure\Http\XeroHttpClient.cs:line 96 at Xero.Api.Infrastructure.Http.XeroHttpClient.Put[TResult,TResponse](String endPoint, Object data) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Infrastructure\Http\XeroHttpClient.cs:line 73 at Xero.Api.Core.Endpoints.Base.XeroCreateEndpoint`4.Put(TRequest data) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Core\Endpoints\Base\XeroCreateEndpoint.cs:line 44 at Xero.Api.Core.Endpoints.Base.XeroCreateEndpoint`4.Create(IEnumerable`1 items) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Core\Endpoints\Base\XeroCreateEndpoint.cs:line 25 at Xero.Api.Core.XeroCoreApi.Create(IEnumerable`1 items) in C:\Users\joe_a84\Downloads\Xero-Net-master\Xero-Net-master\Xero.Api\Core\XeroCoreApi.cs:line 237 at ConnexForXero.XeroApiProvider.XeroProvider.ExecuteBatch() at ConnexForXero.XeroApiProvider.XeroProvider.Execute() at ConnexForXero.TaskScheduler.JMATaskSchedulerProvider.ExecuteXeroProvider() at ConnexForXero.Utilities.RetryUtility.RetryAction(Action action, Int32 numRetries, Int32 retryTimeout) at ConnexForXero.TaskScheduler.JMATaskSchedulerProvider.SyncOrders() at ConnexForXero.TaskScheduler.JMATaskSchedulerProvider.Execute()	`

**Comment by TomLingWu** [comment]
@jmawebtech I got exactly same issue, What's your solution since you closed it.

**Comment by jmawebtech** [comment]
Hi,


On the Xero Core API, do not set summarize orders:


            m_Api = helper.CoreApi();


Please try this code:


 if (m_DeletedCreditNotes.Count() > 0)
            {
                m_Api.CreditNotes.SummarizeErrors(false);
                List<CreditNote> deletedCreditNotes = m_Api.CreditNotes.Update(m_DeletedCreditNotes).ToList();
                if (deletedCreditNotes.Any()) // check for invoices
                {
                    foreach (CreditNote creditNote in deletedCreditNotes)
                    {
                        //Check For any Errors
                        if (creditNote.Errors != null)
                        {
                            foreach (ValidationError error in creditNote.Errors)
                            {
                                m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, String.Format("{0}: {1}", creditNote.Number, error.Message), creditNote.Number));
                            }
                        }
                        else
                        {
                            m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Credit {0} under {1} placed on {2} was deleted successfully!", creditNote.Number, creditNote.Contact.Name, creditNote.Date.Value), creditNote.Number));
                        }
                    }
                }
            }




Joseph Anderson

Director, Customer Success

JMA Web Technologies, Inc.

P: (781) 330-0737

Web: http://www.jmawebtechnologies.com

Store: http://www.jmawebstore.com

________________________________

**Comment by charlesfayal** [comment]
This just pushes the error off to the server..
