### ISSUE TITLE
Invoice Date Range

### ISSUE THREAD

**Issue by jmawebtech** [XeroAPI/Xero-Net#258]
Hi,

I am trying to pull a list of invoices using a date range. Can I have an example, please? My code fails to work and it returns all invoices:

                List<Invoice> newInvoices = m_Api.Invoices.Where("Date > DateTime(2017-3-07)").And("Date < DateTime(2017-3-08).Find().ToList();

**Comment by MJMortimer** [comment]
Hey @jmawebtech, you need to use DateTime(year,month,day) <- values seperated by commas rather than hyphens. Can you please try that and see if it works for you?

**Comment by jmawebtech** [comment]
Thanks! That worked.
