### ISSUE TITLE
Invoices Help

### ISSUE THREAD

**Issue by cpiso** [XeroAPI/Xero-Net#261]
Hi There. 

My code don't seem to return more than 100 invoices (trying to retrieve all invoices since 1 Jan 2015). Can anyone perhaps help me please. What am I doing wrong?

I tried both  
var invoices = private_app_api.Invoices.Find().ToList();
as well as
var invoices = private_app_api.Invoices.ModifiedSince(new DateTime(2015,1,1)).Find().ToList();

without any success. Count coming back every time is 100.

Thank you.

**Comment by MJMortimer** [comment]
Invoices page by default, you need to page through the results, at the moment you're only getting the first page. There is no functionality to retrieve all invoices with this sdk

**Comment by cpiso** [comment]
Thank you MJMortimer. Will give it a try.
