### ISSUE TITLE
When badrequest, HttpWebResponse response trucked message when it is too log.

### ISSUE THREAD

**Issue by klauszhang** [XeroAPI/Xero-Net#264]
please take a look at this class: [Xero.Api.Infrastructure.Http.Response]( https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Infrastructure/Http/Response.cs#L17)

I would add the following line to read the full content of message, when the error message is lengthy.

```
...
L15        ContentType = inner.ContentType;

add->     HttpWebRequest.DefaultMaximumErrorResponseLength = ContentLength; 

            var stream = inner.GetResponseStream();
            if (stream != null)
            {
                Stream = new MemoryStream();
                stream.CopyTo(Stream);
                // rewind
                Stream.Seek(0, SeekOrigin.Begin);
            }    
...

```

Reference:
http://stackoverflow.com/questions/4918107/system-net-httpwebresponse-getresponsestream-returns-truncated-body-in-webexce

**Comment by MJMortimer** [comment]
@klauszhang, do you know the limit that it is being truncated at the moment? What is the HttpWebRequest.DefaultMaximumErrorResponseLength value set to by default?

**Comment by klauszhang** [comment]
@MJMortimer I think it should be 64k by default. Or you can set it to -1 to make it unlimited (i didn't test that). But the line I added fixed my problem.

**Comment by MJMortimer** [comment]
Hey @klauszhang, would you like to add a PR with your desired changes?

**Comment by manicfiddler** [comment]
PR created for this

**Comment by MJMortimer** [comment]
Added in latest merge. New version will be going out shortly
