### ISSUE TITLE
Credit note allocation to invoices

### ISSUE THREAD

**Issue by TOuhrouche** [XeroAPI/Xero-Net#265]
Hi,
Is there any way to allocate a credit note to a given invoice? The `CreditAllocation` currently has no reference to an invoice.

**Comment by MJMortimer** [comment]
Hey @TOuhrouche, 

Take a look at an example test here for how this can be done.  https://github.com/XeroAPI/Xero-Net/blob/master/CoreTests/Integration/Allocations/Add.cs#L14#L30

Cheers, 
Matt

**Comment by TOuhrouche** [comment]
Wow! Thanks a lot for the super fast response :) Will do that now :)
