### ISSUE TITLE
Throttling Errors

### ISSUE THREAD

**Issue by jmawebtech** [XeroAPI/Xero-Net#266]
Hi,

How do I make use of the rate limiter code? My software is trying to import several invoices into Xero in batches of 10, but Xero returns an API throttling error. What am I doing wrong?

`            if (m_Invoices.Count() > 0)
            {
                m_Api.Invoices.SummarizeErrors(false);
                List<Invoice> invoices = m_Api.Create(m_Invoices).ToList();

                if (invoices.Any()) // check for invoices
                {
                    foreach (Invoice inv in invoices)
                    {
                        //Check For any Errors
                        if (inv.Errors != null)
                        {
                            foreach (ValidationError error in inv.Errors)
                            {
                                if (error.Message == "Invoice # must be unique.")
                                {
                                    m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Invoice {0} dated {1} already exists under {2}", inv.Number, ObjectConverter.DateTimeConverter(inv.Date).ToShortDateString(), inv.Contact.Name)));
                                }
                                else
                                {
                                    m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Error, String.Format("{0}: {1}", inv.Number, error.Message), inv.Number));
                                }
                            }
                        }
                        else
                        {
                            m_SyncedInvoices.AddRange(invoices);
                            m_ErrorMessages.Add(new ErrorMessage(MessageSeverity.Info, String.Format("Invoice {0} under {1} placed on {2} was created successfully!", inv.Number, inv.Contact.Name, inv.Date.Value), inv.Number));
                        }
                    }
                }
            }
`

**Comment by MJMortimer** [comment]
Hey @jmawebtech, how do you use the SDK? Do you make use with any of the [example applications](https://github.com/XeroAPI/Xero-Net/tree/master/Xero.Api.Example.Applications) or enter at the [XeroCoreApi class](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Core/XeroCoreApi.cs)

If using one of the example applications, you can just pass true to the includeRateLimiter parameter in the constructor of the example.

If you're instantiating the XeroCoreApi class yourself you can provide a class that uses the IRateLimiter interface which provides methods to throttle your API calls. [There is one included in the solution](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Infrastructure/RateLimiter/RateLimiter.cs)

**Comment by jmawebtech** [comment]
Hi,

I use the XeroCoreApi class. Here is my code:

            var _authenticator = helper.MvcAuthenticator();
            m_Api = helper.CoreApi();

Is this correct?

        public XeroCoreApi CoreApi()
        {
            if (_applicationSettings.Authenticator is IAuthenticator)
            {
                return new XeroCoreApi(_applicationSettings.BaseApiUrl, _applicationSettings.Authenticator as IAuthenticator,
                    _applicationSettings.Consumer, User(), new DefaultMapper(), new DefaultMapper(), new RateLimiter());
            }

            return null;
        }

**Comment by MJMortimer** [comment]
Do you use the CoreApi method more than once or is the resulting XeroCoreApi persisted. If the object is not persisted this would cause the RateLimiter to be reset back to 0 calls in the last minute which would not be aligned with your actual rate limit against the API

**Comment by MJMortimer** [comment]
I'm going to close this issue due to a lack of movement. Please reopen/open a new issue if required
