### ISSUE TITLE
The element 'Amount' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name.

### ISSUE THREAD

**Issue by apathytomorrow** [XeroAPI/Xero-Net#267]
I get this error when searching for an Invoice, then changing a value then updating.

    Failed to process LiveLink: The element 'Amount' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name. Xero.Api.Infrastructure.Exceptions.BadRequestException: The element 'Amount' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name.
       at Xero.Api.Infrastructure.Http.XeroHttpClient.HandleErrors(Response response)
       at Xero.Api.Infrastructure.Http.XeroHttpClient.Read[TResult,TResponse](Response response)
       at Xero.Api.Infrastructure.Http.XeroHttpClient.Post[TResult,TResponse](String endPoint, Object data)
       at Xero.Api.Core.Endpoints.Base.XeroUpdateEndpoint`4.Post(TRequest data)
       at Xero.Api.Core.Endpoints.Base.XeroUpdateEndpoint`4.Update(IEnumerable`1 items)
       at Xero.Api.Core.Endpoints.Base.XeroUpdateEndpoint`4.Update(TResult item)

My code:

    CreditNote existingCreditNote = this.xeroApi.CreditNotes
        .Where("CreditNoteNumber == \"" + creditNoteNumber + "\"")
        .Find()
        .FirstOrDefault();

    if (existingCreditNote == null)
    {
        return;
    }

    existingCreditNote.SentToContact = true;

    this.xeroApi.CreditNotes.Update(existingCreditNote);

Edit: Sorry pasted wrong section originally.

**Comment by MJMortimer** [comment]
This may be a known issue with the Xero API and how the wrapper receives JSON. If any of your invoices have Allocations you may want to set the collection to null. The Allocations won't change but it prevents the wrapper from sending in an incorrect payload

**Comment by apathytomorrow** [comment]
Ok thanks I will try to set the `Allocations` to `null`.

**Comment by apathytomorrow** [comment]
Ah dammit now I cannot edit the Credit Note because it has Allocations...

    Credit Note not of valid status for modification
    This document cannot be edited as it has a payment or credit note allocated to it.

**Comment by MJMortimer** [comment]
@apathytomorrow, yep that's a limitation of the Xero API itself.

**Comment by MJMortimer** [comment]
Are you still have issues with this @apathytomorrow?

**Comment by apathytomorrow** [comment]
@MJMortimer No I've worked around it, many thanks.
