### ISSUE TITLE
Xero-Net on Nuget?

### ISSUE THREAD

**Issue by JonDouglas** [XeroAPI/Xero-Net#27]
Is it possible to get this packaged in a nuspec and put on Nuget as the older repository seems to be the current nuget:

https://www.nuget.org/packages/XeroAPI.Net

https://github.com/XeroAPI/XeroAPI.Net

**Comment by ronanq** [comment]
Hi. We have updated that nuget to reflect that the associated respository is no longer maintained, and we have added a new nuget for this repository: https://www.nuget.org/packages/Xero.API.SDK/
