### ISSUE TITLE
Manual Journal Tax type problem

### ISSUE THREAD

**Issue by thomasmaxiplan** [XeroAPI/Xero-Net#272]
When try to use the api.Create(ManualJournal) as follow:

```
ManualJournal journal = new ManualJournal {
    Narration = journalNarration,
    Date = journalDate,
    Status = journalStatus,
    Lines = journalLines,
    LineAmountTypes = LineAmountType.Inclusive
};

```
I can successfully post the journal but it shows as Amounts are Tax Exclusive when I check from Xero Journal screen which is fine.

If change the LineAmountTypes = LineAmountType.Exclusive then specify TaxType in line items, It returns a validation Exception when I try to post the journal. 

Regards,

**Comment by MJMortimer** [comment]
The issue you're encountering when specifying LineAmountTypes = LineAmountType.Exclusive should be resolved in #277
