### ISSUE TITLE
"Failed to validate signature" when trying to upload a file which contains 'http' in the name

### ISSUE THREAD

**Issue by mpbelov** [XeroAPI/Xero-Net#273]
Reprosteps:
1. Set up partner integration
2. Create a file with 'http' in its name, e.g. "http_something.pdf"
3. Use Attachments endpoint and try to upload it and attach it to any Xero document, e.g. to PO

Expected result: file is uploaded and attached
Actual result: opearation fails with the message says "Failed to validate signature".

If you remove 'http' from file name it works as expected.

**Comment by corientdev** [comment]
+1

**Comment by corientdev** [comment]
no body's there to support or what? it's been pending from last 21 days. Shocking to see this with team XERO

**Comment by MJMortimer** [comment]
I can assure you we're here. 

If you look at the git history you'll find we usually work on this SDK in bursts. 

I've also had a very brief look into this recently in my spare time and from first impressions, it looked to be an issue with the API itself and not necessarily with the SDK. 

By chance have you captured examples of how the oauth signature/signaturebasestring is formatted when using 'http' in a file name vs not using 'http' in the file name to add more context to this issue?

**Comment by corientdev** [comment]
How to get it? Signaturebasestring?

And i had used developer support too directly and their reply says..

`
Hi Vishal
 
The name of the file gets incorporated into the OAuth signature.  Including elements of URL's such as HTTP or special characters can interfere with how the signature is generated and read.  You'll need to make sure that the file names you sync don't use HTTP or HTTPS, and that they only use the dash or underscore for special characters to avoid any problems like this.

 If you have any other questions, please let us know.
 
Kind regards
 
Angela`

**Comment by MJMortimer** [comment]
To get the details of how the SDK is signing the request you'd probably need to pull the source code of the wrapper down and use the example tests or example applications. 

The response you've given from Angela goes into some detail on why I think the issue may be with the underlying API rather than the SDK itself

**Comment by MJMortimer** [comment]
I've looked into this issue further and have found that it is in fact a bug with the Xero API. It will go into our backlog for a fix in the future.

**Comment by mpbelov** [comment]
Hi @MJMortimer. Thanks for details. Any ETA for that fix? Will you post an update here when it is released?

**Comment by corientdev** [comment]
Thanks @MJMortimer  appreciate your efforts!

@mpbelov  I don't think it is gonna get resolved. Because, the system is make like that i believe. Only thing XERO should do is document this as exception. So that we can consider it while building any app.

**Comment by MJMortimer** [comment]
@mpbelov I can't give an exact time frame for the fix unfortunately. 

@corientdev It will be resolved in due time. As I'm sure you can expect, the dev team for the API (myself included) are always busy and so the bug will be prioritized and fixed at some stage in the future

**Comment by corientdev** [comment]
Amazing @MJMortimer . Also i wanted to ask one thing. What are the feature wise difference between minimal SDK and Standard SDK. The only thing written there is it stores token in sqlite which doesn't explain what it is exactly. Please help!

**Comment by MJMortimer** [comment]
The difference is essentially exactly that. 

The minimal package contains all of the core SDK components as well as the example application implementations in the Xero.Api.Example.Applications library. 

The other package contains all of those things as well an example sqlite token store in the Xero.Api.Example.TokenStores library. 

You can see the full details of differences in the 2 nuspec files checked into source control

**Comment by corientdev** [comment]
Thank you! Much appreciated.. 

I believe it is out of my scope currently as it has to deal with partner app. I develop Private app mostly so may be will look into it when required.

**Comment by corientdev** [comment]
I get same error if the filename contains "[" or "]". Seems there is some serious issue with xero API

**Comment by SidneyAllen** [comment]
We are archiving this repository in conjunction with our deprecation of OAuth 1.0a. If you wish use Xero-Net going forward you have the option of forking the Xero-Net repository. We recommend moving to Xero-NetStandard SDK for OAuth 2.0 as it will be supported and maintained going forward. https://github.com/XeroAPI/Xero-NetStandard

If you need more time to complete your migration to OAuth 2, please contact api@xero.com for assistance.
