### ISSUE TITLE
Get multiple invoices by guid? Is there a way in sdk without using Or operator?

### ISSUE THREAD

**Issue by corientdev** [XeroAPI/Xero-Net#280]
Get multiple invoices by guid? Is there a way in sdk without using Or operator?

`GET https://.../Invoices?ContactIDs=3138017f-8ddc-420e-a159-e7e1cf9e643d,4b2df4a1-7aa5-4ce3-9e9c-3c55794c5283`

Like the way it is shown in documentation (Comma seperated)

Basically goal is i don't want to waste my limited hits that i get

**Comment by MJMortimer** [comment]
Hey @corientdev,

One of my latest updates added functionality for this. You can find examples of how to use the various invoice filters [here](https://github.com/XeroAPI/Xero-Net/blob/master/CoreTests/Integration/Invoices/Find.cs#L30-L65)

Let me know if there are any issues with the new functionality.

**Comment by corientdev** [comment]
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<title>IIS 8.5 Detailed Error - 404.15 - Not Found</title> 
<style type="text/css"> 
 
</style> 
 
</head> 
<body> 
<div id="content"> 
<div class="content-container"> 
  <h3>HTTP Error 404.15 - Not Found</h3> 
  <h4>The request filtering module is configured to deny a request where the query string is too long.</h4> 
</div> 
<div class="content-container"> 
 <fieldset><h4>Most likely causes:</h4> 
  <ul> 	<li>Request filtering is configured on the Web server to deny the request because the query string is too long.</li> </ul> 
 </fieldset> 
</div> 
<div class="content-container"> 
 <fieldset><h4>Things you can try:</h4> 
  <ul> 	<li>Verify the configuration/system.webServer/security/requestFiltering/requestLimits@maxQueryString setting in the applicationhost.config or web.config file.</li> </ul> 
 </fieldset> 
</div> 
 
<div class="content-container"> 
 <fieldset><h4>Detailed Error Information:</h4> 
  <div id="details-left"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;RequestFilteringModule</td></tr> 
    <tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;BeginRequest</td></tr> 
    <tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;ExtensionlessUrlHandler-Integrated-4.0</td></tr> 
    <tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr> 
     
   </table> 
  </div> 
  <div id="details-right"> 
   <table border="0" cellpadding="0" cellspacing="0"> 
    <tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;http://api.xero.com:80/api.xro/2.0/Invoices?unitdp=4&amp;page=1&amp;ids=31cc4e83-6ab8-4e61-ba49-6ce714f36aa3%2c823b8e3b-9882-45ca-ab28-88802b900d0c%2c2456f5f3-f3c4-4db5-8e2e-22c24843acc8%2c8ba3725d-8a52-4d11-a5b7-d7fa757156dc%2c641e8b9b-1140-4718-9655-036733ee93d4%2c4bed2868-bef9-4c79-891f-17b1e2d99fac%2cf44fd736-804f-4ba0-afd9-860770449eff%2cde572d66-8000-4048-919d-7a7182d2321c%2cc2318104-b7c7-40a5-8b48-1b0b9c9ac834%2c54225208-6cc0-4592-a6c6-e611905f894f%2cabe22b80-2c44-4806-85bb-98a94eeab581%2c041a174c-d899-42ad-8512-99314007a6c0%2cf3bb71ac-b2e6-47ef-aa35-cb96a133c055%2cea6e5800-7572-4f0c-bdab-b3239239a379%2c1f769669-b5c5-4c81-a069-7b61a7bbb413%2ca0fcb6da-93f6-4def-96fd-a27b448e391c%2c70bf6661-71d0-47fd-8fca-1db7fa0d2fbf%2c34227894-4014-4fb1-bbfc-fc11ee2741cc%2ce699fed6-0b53-40fe-bf56-367d50abeb14%2ce48079ac-8063-46ec-98b0-a1d139d54983%2c0510883c-2d12-4e06-ba23-ca5468fdb2ba%2cf957ba23-c5a7-4a61-8ee8-8126365f14eb%2cc74b4a71-7231-4d4e-9d83-d80dcd73ff94%2c8e71241d-0ee6-409a-b839-6534f14ac185%2ce4c8c4bf-d857-40d9-b49a-116bf33a94b8%2c7426cf8e-a96d-45f6-ba4c-7f4a82055b97%2c36254272-453a-477a-b3ef-1d53a6ecaaef%2c95f21b5f-f32c-4006-b8f4-62c995bfb71a%2c76e94ae2-9719-407d-a917-fdbfa4f3eae5%2c053d7bc0-ed0d-4500-977e-b0903c37dfcb%2cf7b30c6e-cd92-415f-a04a-54a731721a1b%2c44c14cc5-d951-4d1d-a51f-b96ff2607f5b%2c8ee6d0fe-bff0-49da-9523-37bdf9355362%2c4932e595-7a1c-45ee-bfaa-9425a27e6797%2cab7ad60a-dd14-4893-9c24-1a6021c8e77e%2c2a2277a1-348e-44f2-bd66-86a28053fab4%2c9ff7ac55-ac73-4d9b-be71-4ebe7eea6a6f%2cab1be27a-048d-43cb-917a-9caa2fb36154%2c4c16781a-d663-44a9-a8ab-20f4e5e24eba%2cea11dc77-ea11-41a9-9b42-039dc5d1dc1f%2ccc31d966-a3d9-4a06-9ab0-16d4293baeb4%2ce634e3fd-4828-4b25-8fe8-2eec6c7f8572%2c11be05b6-d2a1-4b52-a2d5-4a10b426840e%2c01dc4977-69f8-46d3-958e-e65c2e44bcb3%2cbf4e4276-3373-4aac-8c31-d0c1d7388f2a%2c66afb0ed-b034-45e5-a9ae-ecd37ebcadde%2c3662aa98-3e97-4a5c-a185-c88b5822bd62%2c67fff37b-956e-42ec-aefe-8694d9f4159f%2cd4e9cd87-d170-47b0-a086-55eb7f406668%2c8d5954a1-3841-43e9-aede-72416abb467f%2c7eef13dc-f0a7-47ca-990d-8f4b8c4cfeb7%2cda78feca-df7d-4ef9-a689-c72e769e1521%2c603c761f-655a-421b-99c9-13e69176fc5b%2c4ccd48af-ae3b-410a-bfab-122a997ea799%2c42a6c661-63ab-47b6-be7b-6060cd5ff979%2cbaa15f58-1a0f-415b-91b9-e3c608f2a77c%2c2036f48e-82e0-4d08-825d-33139d3d4be4%2c1594bd6c-da14-442e-8aaa-3a717e50202d%2c289c58e3-43f8-47fb-a81c-ad1aacb292ea%2c11c677cc-ccd1-4ea6-90fa-25ec549145df%2c5c6b0a8d-151a-477b-9e84-f644472438d7%2c78e69c06-46a6-44ba-840f-5e46185b3194%2c5d3c1d4a-bad2-4ed7-ba32-4a48cdfd12f1%2c739a7bf2-1173-4174-a1fd-181e3445b87f%2ce009128a-2d5b-4943-bd79-0060567d7993%2cc70d81b2-418e-425f-bed6-7360d18b4c22%2c7ce76732-d726-4cae-b960-dbef4b17a130%2cc34139cc-b145-476e-98ea-e9441ad9aab7%2cf19b219f-71c6-47d4-a162-e3a099b9a483%2c59542fec-861c-476a-b700-8beb28135ebb%2c2e7b9507-6bca-496b-b3e7-cfa5de69c6b0%2ceb204c08-29b7-484e-b076-4f92f7818187%2c31d2f934-1af2-425f-85b6-f36d52d99d80%2c4b28adbe-c821-4406-b752-d10600fbb62d%2c360cca88-1f9c-4856-980f-d9d587ea6966%2cec5bc56e-149d-4831-af8a-34af1dadad07%2cd0524304-2bf8-40ea-8d4b-bbd066bd2e00%2c8b26ca7d-c9a4-4c78-9f15-d1f70fb0b3dc%2c293c1dc9-692d-4e99-ae96-ea27a4ef9e40%2ca377c03a-3b8b-48dd-a41f-feca94689312%2caf1f54de-42ef-4296-8ee1-d657f632e3b0%2c94b36487-586b-48ac-bc63-95b50d2d1c5f%2cfba1e816-7bcf-45e1-8ea0-d85246dfa9b9%2cfe18090a-b59d-4182-a400-42c700dbedf1%2c0684df3b-3f52-49da-ae58-5eec51a7fb9a%2c8ca0a624-b59e-415a-a17d-eadeca0c14dd%2c0972e797-b073-41fa-9466-e33f06a9d3ce%2c353eb1a3-8a03-4162-b9b9-b3df11996cad%2c5be7cbdb-ffce-4d80-936d-4e792ce32c59%2c271dba3c-36f8-48aa-8729-8c10abee4577%2c94ef1360-6e67-4bad-95ea-5a17bc616982%2c85f2f8cc-4a81-41b8-a894-363c740af41e%2cdf9ea7f8-33df-4535-8ad1-e8d28fb583fc%2c24bc231e-d10c-4b3d-b728-e18c7d21298d%2cd9eea1a3-3e42-4ce0-87f1-5d0703ad6b8e%2c6fd2e75f-ee59-4af6-b077-6797891d8291%2c114f4847-21d3-4326-ade0-3daf8c034ee1%2cc4990587-f4b9-4b60-baa7-e8c62fdb0ca4%2c86cf7746-17a0-4972-b9af-b2864712328b%2cfdb396b0-1ac6-4f6f-af82-0afa4c7c69e8</td></tr> 
    <tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;C:\inetpub\wwwroot\api\v2.203.536-20170524.232741\api.xro\2.0\Invoices</td></tr> 
    <tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr> 
    <tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr> 
     
   </table> 
   <div class="clear"></div> 
  </div> 
 </fieldset> 
</div> 
 
<div class="content-container"> 
 <fieldset><h4>More Information:</h4> 
  This is a security feature. Do not change this feature unless the scope of the change is fully understood. You can configure the IIS server to reject requests whose query string is greater than a specified value. If the request's query string is greater than the configured value, this error is returned. If the allowed length of the query string needs to be increased, modify the configuration/system.webServer/security/requestFiltering/requestLimits@maxQueryString setting. 
  <p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=404,15,0x00000000,9600">View more information &raquo;</a></p> 
   
 </fieldset> 
</div> 
</div> 
</body> 
</html> 
 (NotFound)`

This is the error while using it to get detail of 100 invoices.

Maximum permitted request?

**Comment by MJMortimer** [comment]
Ah yep, there will be a limit based on how long a standard url query parameter string can be with IIS. I think the default limit is around 2048 characters long. You will want to split your request down to around 50 id 'chunks' to remain within this limit.

**Comment by corientdev** [comment]
yeah we should mention it in docs. That will improve the knowledgebase. And one more thing is there any bulk retrival for credit notes?

**Comment by MJMortimer** [comment]
I'll make sure to bring up the docs improvement with the team. 

As for the credit notes, we don't currently have any support for filters like this or paging. It's in the pipeline and I'll be sure to add it to this sdk as soon as it's available

**Comment by corientdev** [comment]
Thanks man!

Thanks for the help..

Cheers!

**Comment by PabloInNz** [comment]
Any update on bulk retrieval for credit notes ? Is the best way currently to use an or query ?
Thanks

**Comment by MJMortimer** [comment]
@PabloInNz, nope, unfortunately there is no functionality like this on Credit Notes at this stage. Your best bet is using some ORs in a where clause. You may however find that if you include too many ORs in your where clause that you can run into performance problems. If you're not coming close to rate limiting issues I'd suggest getting them individually
