### ISSUE TITLE
Bank account routing and account number need to be type String

### ISSUE THREAD

**Issue by thevalyreangroup** [XeroAPI/Xero-Net#282]
Currently Xero.Api.Core.Model has a type for BankAccount with a few values.  Both the RoutingNumber and AccountNumber are declared as Int32, but they need to be a String for the API to accept the request.  You cannot convert large account numbers to an Int32 without overflow.  I have confirmed this by building my own DLL with them as Strings and it works.

**Comment by MJMortimer** [comment]
Hey @thevalyreangroup, 

Would you like to open a pull request with your desired changes?

**Comment by thevalyreangroup** [comment]
@MJMortimer Done!

**Comment by MJMortimer** [comment]
Resolved in #287 Thanks @thevalyreangroup
