### ISSUE TITLE
SummarizeErrors(False) doesn't show certain validation errors

### ISSUE THREAD

**Issue by DBLogic** [XeroAPI/Xero-Net#285]
I'm calling 
`
Core.SummarizeErrors(False)
Dim lstSent = Core.Create(lstAccounts)
`
This doesn't appear to give any indication that any of my accounts has had a validation error.
All the accounts in lstSent have Ok validation status and no validation errors or warnings, and the new account doesn't appear in Xero.

Then if I call that with the same accounts without Core.SummarizeErrors(False) it throws a validation exception as expected, with a validation error of:
"Account Code is too long. Maximum of 10 characters allowed"

I may have missed another property but it looks like not all validation errors are being returned when SummarizeErrors(false) is used.

**Comment by MJMortimer** [comment]
Hey @DBLogic,

At this stage, you can only add or update one account at a time. You can find this information in the PUT and POST details on the [Accounts documentation page.](https://developer.xero.com/documentation/api/accounts)
If you provide a list of accounts to the accounts endpoint, the API will only process the first one.

You also seem to have stumbled across a bug with using SummarizeErrors=false and Account create/update where it does not populate the StatusAttributeString property correctly. I'll be sure to raise this bug with the rest of the development team. For the time being you should avoid using SummarizeErrors=false with the Accounts endpoint or at least rely on the Errors/Warnings properties being empty or not as a workaround

**Comment by DBLogic** [comment]
Creating linked transactions also does not show any errors when SummarizeErrors is used

**Comment by MJMortimer** [comment]
Linked transactions also only accepts single linked transactions in PUT and POST operations. I'll raise with the rest of the team that linked transactions doesn't support SummarizeErrors, but as you can only operate on a single linked transaction at a time you don't really need to set SummarizeErrors to false. If you leave it as true and catch the validation exception that is thrown when trying to create or update an invalid linked transaction. The validation errors will be returned in the validation exception. 

SummarizeErrors is really only useful when you are creating or updating batches and you want to know which specific items in the batch have failed

**Comment by SidneyAllen** [comment]
We are archiving this repository in conjunction with our deprecation of OAuth 1.0a. If you wish use Xero-Net going forward you have the option of forking the Xero-Net repository. We recommend moving to Xero-NetStandard SDK for OAuth 2.0 as it will be supported and maintained going forward. https://github.com/XeroAPI/Xero-NetStandard

If you need more time to complete your migration to OAuth 2, please contact api@xero.com for assistance.
