### ISSUE TITLE
xero api

### ISSUE THREAD

**Issue by mtimuni** [XeroAPI/Xero-Net#290]
I am having a an issue with xero api. am getting this error. please assist.
An unhandled exception of type 'Xero.Api.Infrastructure.Exceptions.UnauthorizedException' occurred in Xero.Api.dll

**Comment by MJMortimer** [comment]
Hey @mtimuni, that error is normally present when you're getting the OAauth signing incorrect. Without disclosing any sensitive information, are you able to give me an example of how you are setting up and trying to use the SDK?

**Comment by MJMortimer** [comment]
I'm going to close this issue due to a lack of movement. Please reopen/open a new issue if required
