### ISSUE TITLE
No response from item delete

### ISSUE THREAD

**Issue by BlairCentrix** [XeroAPI/Xero-Net#291]
Quite often when calling the Delete Item endpoint with this wrapper we are getting a web exception timeout due to not getting the 204 response code back from the sent request.  I have emailed the Xero help desk which was not much help with this problem.  I am using the line:

Api.Items.Delete(item);

Where Api is the XeroCoreApi object.  Using this object to Post, update items, invoices and new contacts does not cause any problems it is only when deleting existing items are we getting issue.  I am noticing that the item is actually getting deleted from Xero.  We are just not getting the response back.

And to work around this i have had to create some inefficient code to reattempt to delete the item to then catch the NotFoundException.

Thanks

**Comment by MJMortimer** [comment]
Have you been able to inspect the web traffic with a tool like Fiddler to see whats happening with the request? It sounds like this may not be an issue with this SDK but more with the underlying API itself getting hung up

**Comment by MJMortimer** [comment]
I'm going to close this issue due to a lack of movement. Please reopen/open a new issue if required
