### ISSUE TITLE
Zero based enums

### ISSUE THREAD

**Issue by MatthewSteeples** [XeroAPI/Xero-Net#292]
Unless the upstream API requires it, please can we refrain from having valid 0 value enums (such as Account in ObjectGroup). It makes quite difficult to work out whether the bug is because you're using the wrong value, or whether you just haven't set a value in the first place

This is especially highlighted when a new value is added upstream because, without a valid enum to translate it into (until the wrapper gets updated) it will just resolve to a 0

**Comment by MJMortimer** [comment]
Do you think it would be a good idea to go back through all enums for types and statuses etc, add a `-1 Unknown` value, and bump the default value up to 1 for all the current 0 based ones?

**Comment by MatthewSteeples** [comment]
That's what we do internally with our enums. The problem is that technically it's a breaking change (as people could be depending on the numerical values somewhere)

**Comment by MJMortimer** [comment]
Hey @MatthewSteeples ,

As mentioned in our readme, we won't be looking to add any new features to this SDK.

> We will continue to periodically review pull requests to fix small issues and watch for secruity issues until December 2020. Maintenance does not include adding new features, oauth 2 support or large refactoring of the code base.

Unfortunately this change will fall outside the definition of the types of changes we're looking to make. If you want this functionality to be added, you'll have to make the changes in your own fork and use your own nuget package
