### ISSUE TITLE
Xero.API.SDK.Minimal nuget dependency failure

### ISSUE THREAD

**Issue by Tyf0x** [XeroAPI/Xero-Net#294]
The nuget package of Xero.API.SDK.Minimal v2.2.1.6 fails to load due to a case-sensitivity typo in the Newtosoft.Json dependency.

The [line in the minimal.nuspec](https://github.com/XeroAPI/Xero-Net/blob/master/minimal.nuspec#L19) file should mention `<dependency id="Newtonsoft.Json" version="[9.0.1,)"/>` instead of `<dependency id="NewtonSoft.Json" version="[9.0.1,)"/>`.

This prevents VS2015 to restore the package and ultimately the project to build.

**Comment by MJMortimer** [comment]
This will be resolved in #297
