### ISSUE TITLE
AmericanPayrollAPI Employee endpoint missing many objects

### ISSUE THREAD

**Issue by thevalyreangroup** [XeroAPI/Xero-Net#296]
As you can see below, the AmericanPayroll is missing more than half the the employee data.  Most important to me would be the Taxes, Address, and PayTemplate, but why is not all of it there?

![screen shot 2017-09-12 at 12 46 47 pm copy](https://user-images.githubusercontent.com/22800795/30338707-7f2045bc-97ba-11e7-8e84-05c5cfbacb2f.png)

**Comment by MJMortimer** [comment]
Hey @thevalyreangroup, have you been able to inspect the underlying http response to see if these properties are returned by the Xero API? If they are, there is probably a just an issue with deserialization. If not, then the SDK will not be able to return those details as they aren't provided.

**Comment by thevalyreangroup** [comment]
@MJMortimer  I haven't inspected the response, but according to the docs, they should be.  https://developer.xero.com/documentation/payroll-api-us/employees#PayTemplate

**Comment by MJMortimer** [comment]
Did you receive a single employee or a list of employees? 

I'm not entirely up to speed with the ins and outs of the US payroll API but from XML example on the docs page you linked, it looks as though retrieving a list of employees may return less data than retrieving a single employee

**Comment by thevalyreangroup** [comment]
@mjmortimer This particular case is involving one employee using the where() query.

**Comment by MJMortimer** [comment]
The where filter is only functional with the accouting API. Do you have an example of the line of code you use to retrieve the employee?

**Comment by thevalyreangroup** [comment]
I disagree, this function works as is, i just don't get all the objects it should return in the response.

         ` var payrollApi = new Xero.Api.Payroll.AmericanPayroll("https://api.xero.com/payroll.xro/1.0", new PrivateAuthenticator(cert),
                new Consumer("XXX", "XXX"), null,
                new DefaultMapper(), new DefaultMapper());
            
            var emgr = new EmployeeManager();
            var emps = emgr.GetAllActiveKeepers();

            foreach (var e in emps)
            {
                System.Threading.Thread.Sleep(500);
                var xE = payrollApi.Employees.Where("Email=\"" + e.Email + "\"").Find().FirstOrDefault();
                if (xE == null)
                {
                    continue;
                }
                e.InternalId = xE.Id.ToString();/*
                e.Address = xE.HomeAddress.StreetAddress;
                e.City = xE.HomeAddress.City;
                e.State = xE.HomeAddress.State.ToString();
                e.ZipCode = xE.HomeAddress.ZipCode.ToString();
                e.Wage = xE.SalaryAndWages[0].HourlyRate;
                e.Birthdate = xE.DateOfBirth;
                e.BankAccount = xE.PaymentMethod.BankAccounts[0].AccountNumber;
                e.BankRouting = xE.PaymentMethod.BankAccounts[0].RoutingNumber;
                e.BankName = xE.PaymentMethod.BankAccounts[0].AccountHolderName;*/
                Console.WriteLine(e.FirstName + " " + e.LastName);
                emgr.SaveEmployee(e);
            }`

I commented all of those lines because all of those objects are null.  But the simple things (email, Id, Name, etc) all work

**Comment by MJMortimer** [comment]
Ah, you're correct, Employees does support the where clause. I think it's one of the few payroll endpoints that does. 

After retrieving the employee with this line
```
var xE = payrollApi.Employees.Where("Email=\"" + e.Email + "\"").Find().FirstOrDefault();
```
Can you please try retrieve the employee again in a following line using
```
xE = payrollApi.Employees.Find(xE.Id);
```
This will tell us whether the extra details you want are only returned when receiving an individual employee rather than a filtered list of employees. 

If retrieving the employee by Id does give you back all of the extra details then you could also try adding `.Page(1)`  to your orignal where filtered query so it looks like this 
```
var xE = payrollApi.Employees.Where("Email=\"" + e.Email + "\"").Page(1).Find().FirstOrDefault();
```

It's common for queries requesting single entities and queries using paging to retrieve more information than filtered 'find all' does

**Comment by thevalyreangroup** [comment]
That did indeed work, i will investigate further to be sure all objects are there that should be.  Thanks!

**Comment by MJMortimer** [comment]
No problem!
If your investigation is all good, could you please close this issue, if not feel free to post issues from your investigation here

**Comment by MJMortimer** [comment]
I'm going to close this issue, if there are any ongoing problems they can be opened as separate issues
