### ISSUE TITLE
Upgrade path/guide for older C# library

### ISSUE THREAD

**Issue by davidkeaveny** [XeroAPI/Xero-Net#298]
I am looking to update our partner app from the old library (https://github.com/XeroAPI/XeroAPI.Net) to support the removal of client certificates; it rather looks like I need to move to the new .NET library - is this correct, and if so, is there a migration guide?

**Comment by MJMortimer** [comment]
There is no guide that I am aware of. You could try asking in our [community site](https://community.xero.com/developer) to see if there are other developers who have gone through the switch process
