### ISSUE TITLE
Australian Payroll API - PayItems

### ISSUE THREAD

**Issue by craigyd** [XeroAPI/Xero-Net#300]
Hi

I am using PayItems.Find() to get all the payitems, everything except the earningsrates are being returned, all I get back is an empty array. I am testing against the sandbox and when I use the api previewer it returns what is expected.

Anyone have any ideas where I might be going wrong?

**Comment by shaun5004** [comment]
Hi

I just came across the same issue. After some digging around it looks like 2.2.1.7 introduced this issue so use 2.2.1.6 instead.

https://github.com/XeroAPI/Xero-Net/commit/f7213975980561ad2032b6ea24c0ce0b1bdf01fc#diff-08b4197b7c65a8671803914198506c5c is the commit in question 

I have forked 2.2.1.7 and fixed the issues for the AU payroll as I need this working for a project.

It also worth noting that 'IsReportableAsW1' is missing from all versions of this C# API, not sure if you need that or not.

Thanks

**Comment by MJMortimer** [comment]
Hey @shaun5004, would you be able to open a pull request for the updated functionality?

**Comment by shaun5004** [comment]
Hi @MJMortimer 

I have raised https://github.com/XeroAPI/Xero-Net/pull/307 to fix the issues with EarningRates

**Comment by MJMortimer** [comment]
Thanks @shaun5004, it's been merged and will be released to Nuget shortly. If there are any more issues regarding this please open a new Issue
