### ISSUE TITLE
Fluent Query Methods use Side Effects

### ISSUE THREAD

**Issue by richardlawley** [XeroAPI/Xero-Net#301]
The use of your fluent methods suggests that you should be able to perform the following code to retrieve all invoices for a specific customer.

```csharp
var query = _api.Invoices;
string where = $"Type == \"ACCREC\" AND (Status == \"AUTHORISED\" OR Status == \"PAID\") AND Contact.ContactId == Guid(\"{customerId.Value}\")";

IEnumerable<Invoice> pageContents;
int page = 1;
do
{
	pageContents = query.Page(page);
	// Do something with results
	page++;
} while (pageContents.Count() == 100)
```

However, this doesn't perform as expected - the query is discarded after the first execution and the second "page" just returns all unfiltered invoices.  I have corrected my code by doing the filtering on every page, but this is something which may well catch someone else out.

**Comment by MJMortimer** [comment]
Hey @richardlawley, 
There is a note about this in the 'Things to note section of the readme'
