### ISSUE TITLE
Send list of CreditNoteAllocation's to Xero

### ISSUE THREAD

**Issue by Izanne** [XeroAPI/Xero-Net#303]
Hi!

Is there support for sending a list of creditnoteallocations to Xero? I can't seem to get it to work. At the moment I can only send one at a time, and that is taking forever for large lists.

Thanks :-)

**Comment by MJMortimer** [comment]
Unfortunately the functionality is not currently available via the API.

Feel free to start a vote for the functionality via our [uservoice page](https://xero.uservoice.com/forums/5528-xero-accounting-api)
