### ISSUE TITLE
Add date range to querying

### ISSUE THREAD

**Issue by axtens** [XeroAPI/Xero-Net#314]
.ModifiedSince() is okay, but suppose I want the invoices between 2017-12-01 and 2017-12-31? Currently I get everything and filter.

**Comment by russelldear** [comment]
You can use the Where clause for this already - something like invoices.Where("UpdatedDateUTC>DateTime.Parse(\"2017-12-01\") AND UpdatedDateUTC<DateTime.Parse(\"2017-12-31\")") - but happy to consider PR's for some syntactic sugar over the top of that.

Requests using .ModifiedSince() will perform better, though, so maybe try it out before changing.

**Comment by MJMortimer** [comment]
This issue seems to be resolved. Please reopen/open a new issue if required
