### ISSUE TITLE
PurchaseOrder.ExpectedArrivalDate cannot be set to null

### ISSUE THREAD

**Issue by simonlaszcz** [XeroAPI/Xero-Net#315]
ExpectedArrivalDate cannot be set to null
 e.g.
                    po = xeroapi.PurchaseOrders.Find(id);
                    po.ExpectedArrivalDate = null;
                    xeroapi.PurchaseOrders.Update(po);
                    po = xeroapi.PurchaseOrders.Find(id);

After the second find, the property is still set

The causes further problems in that the PO cannot be deleted when the ExpectedArrivalDate is set

**Comment by MJMortimer** [comment]
Hey @simonlaszcz, apologies for the incredibly long delay on this one. I've just looked into this now and there is actually an underlying issue with the API that is preventing the ExpectedArrivalDate from being removed. I also think it's a bug that you can't delete a PurchaseOrder when the ExpectedArrivalDate has been set. 
I'm going to raise both with the team.

**Comment by SidneyAllen** [comment]
We are archiving this repository in conjunction with our deprecation of OAuth 1.0a. If you wish use Xero-Net going forward you have the option of forking the Xero-Net repository. We recommend moving to Xero-NetStandard SDK for OAuth 2.0 as it will be supported and maintained going forward. https://github.com/XeroAPI/Xero-NetStandard

If you need more time to complete your migration to OAuth 2, please contact api@xero.com for assistance.
