### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by jmawebtech** [XeroAPI/Xero-Net#318]
Hi,

I received an email that Xero will only take TLS 1.2 requests. Can I just upgrade my solution to .NET 4.61 or do I need an updated version of this assembly?

**Comment by MJMortimer** [comment]
I'll get in touch with those in the know regarding the TLS upgrade and get back to you

**Comment by MatthewSteeples** [comment]
@jmawebtech Simply upgrading your app to .net 4.6.1 is enough, as the setting is at the app level not the assembly level.

Additionally, if you are on .net 4.5 this is also supported, but you need to set TLS 1.2 as the default (before making your request):
`System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

**Comment by MJMortimer** [comment]
Nice one, thanks @MatthewSteeples!

**Comment by FACAMK** [comment]
@MatthewSteeples just a quick question: 
Will this work with the Xero.Api.Core.XeroCoreApi with a PrivateAuthenticator?

**Comment by MatthewSteeples** [comment]
@FACAMK Sorry, didn't see this reply. It will work across the board. It's an app-level setting that you only need to apply once (or it's already the default in .NET 4.6.1)

**Comment by MatthewSteeples** [comment]
Some more details have been published [here](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls)

**Comment by Munies** [comment]
Hi I am using console application Au payroll. How can i set or upgrade the TLS version. And where i need to  use this command. System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

**Comment by MJMortimer** [comment]
@Munies if you just add that line at the start of your console app set up it should fine

**Comment by Munies** [comment]
Thank you @MJMortimer now its ok.. I have another doubt xero payroll POST api not working any source code or sample is there please share me.

**Comment by MJMortimer** [comment]
@munies can you please provide some reproduction steps for your payroll failure? Possibly a code snippet or runnable example? How is it failing?

**Comment by Munies** [comment]
@MJMortimer, 
I am using xero payroll api for Employee creation and Timesheet information. I can able to GET API for payroll employee Information but unable to use POST api. Following source and api. And i can able to use Previewer it getting positive response at same data unable to achieve through my source.  

   Organization : Demo Company (AU)
   Source : https://github.com/XeroAPI/XeroAPI.Net/tree/payroll
   PayrollAPI : https://api.xero.com/payroll.xro/1.0/Employees
   
  Image Details:
  1.POST --- Source code 500 error.
  2.POST fails --- API Call Details
  3.POST previewer --- Same data or information to pass previewer its working  
![1 post](https://user-images.githubusercontent.com/40913563/42516908-35a03960-847c-11e8-9124-4c2748213b48.png)
![2 post fail](https://user-images.githubusercontent.com/40913563/42516910-35d68150-847c-11e8-8bc0-25cd03dea9c8.png)
![3 post previewer](https://user-images.githubusercontent.com/40913563/42516911-361eafb6-847c-11e8-9ec8-8cebddaf457c.png)

**Comment by MJMortimer** [comment]
@munies This link you've provided https://github.com/XeroAPI/XeroAPI.Net/tree/payroll links to our old deprecated SDK. 

Which SDK are you you having trouble with?

**Comment by Munies** [comment]
Thanks @MJMortimer for your reply. Can you share any new link or source for AU payroll api..?

**Comment by MJMortimer** [comment]
@munies, can you please open a new issue and we can take the discussion there?
