### ISSUE TITLE
Token Renewal not working, token is not valid

### ISSUE THREAD

**Issue by tqrecords** [XeroAPI/Xero-Net#319]
I have a partner application registered with Xero and the Token Renewal never seems to work. Users are being forced to re-authenticate every time. I'm storing tokens in the database as a serialized string. An expired token is read and it appears like the api was written to auto-magically renew the token. The code fails on this method here:

`protected override IToken RenewToken(IToken sessionToken, IConsumer consumer)
        {
            var authHeader = GetAuthorization(sessionToken, "POST", Tokens.AccessUri, null, null, true);
            return Tokens.GetAccessToken(sessionToken, authHeader);
        }`

Exception being thrown is:
`oauth_problem = token_rejected & oauth_problem_advice = The access token is not valid`

I'm hoping someone can help with this, the support over on the Xero Community is brutal.

**Comment by MJMortimer** [comment]
This has been answered in one of the community posts https://community.xero.com/developer/discussion/71511115
