### ISSUE TITLE
Heap Corruption Exception

### ISSUE THREAD

**Issue by piotrzarek** [XeroAPI/Xero-Net#320]
Hello,

Instantiating the XeroApiCore as below:

```
new XeroCoreApi("https://api.xero.com",
                        new PrivateAuthenticator(new X509Certificate2(certificate, certificatePass)),
                        new Consumer(consumerKey, consumerSecret),
                        null,
                        new DefaultMapper(),
                        new DefaultMapper());
```

from within the MVC application causes the following crash on the Windows Server 2012 Standard:

Faulting application name: w3wp.exe, version: 8.0.9200.16384, time stamp: 0x50108835
Faulting module name: ntdll.dll, version: 6.2.9200.22254, time stamp: 0x598d309d
Exception code: 0xc0000374
Fault offset: 0x00000000000da535
Faulting process id: 0x1018
Faulting application start time: 0x01d3b175a673b609
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 2eb520fd-1d69-11e8-9442-0282cefac81c
Faulting package full name: 
Faulting package-relative application ID:

We're now therefore unable to run Xero integration on our production environment. Please advice.

Best Regards,
Piotr Zarek

**Comment by MJMortimer** [comment]
Hey there, I've never heard of this problem occurring with users of the SDK before and so don't really have any guidance to give. The dll that's failing is a windows system dll so is it possible the problem is with that dll alone and the SDK is just exposing the problem?

**Comment by MJMortimer** [comment]
I'm gonna close this issue due to inactivity. Please reopen if the issue persisis
