### ISSUE TITLE
Endpoints unable to mock in the following scenario

### ISSUE THREAD

**Issue by RichardUcsts** [XeroAPI/Xero-Net#321]
While it's easy to mock a simple endpoint request like Create, you can't mock for the following scenario

XeroApiHandle.BankTransactions
                         .UseFourDecimalPlaces(true)
                         .SummarizeErrors(false)
                         .Create(batchToSend);

Because the UseForDecimalPlaces and SummarizeErrors are not overrideable. 

Another option would be to create an implementation for IBankTransactionEndpoint, but it's pointless because UseFourDecimalPlaces returns a BankTransactionEndpoint instead of an IBankTransactionEndpoint

**Comment by MJMortimer** [comment]
If you're keen to submit your changes in a pull request I'll be happy to accept and merge.

**Comment by RichardUcsts** [comment]
Fantastic, thank you.

**Comment by MJMortimer** [comment]
Closed due to inactivity
