### ISSUE TITLE
TSL 1.1 or TSL 1.2

### ISSUE THREAD

**Issue by FACAMK** [XeroAPI/Xero-Net#322]
I am using this SDK to work with Xero (private application with certificate) and they've released a statement that we need to do some changes for TSL 1.0

My question is, does this SDK support that requirement?

.Net 4.6.1
Xero.API.SDK.Minimal.2.2.1.1

**Comment by MatthewSteeples** [comment]
See #318 for details

**Comment by FACAMK** [comment]
Thank you Matthew.
