### ISSUE TITLE
Token is empty

### ISSUE THREAD

**Issue by 0Rudy0** [XeroAPI/Xero-Net#329]
Hello!
Until a few days ago everything worked just fine but today when I tried to connect to the Xero app I noticed that retrieving token (https://api.xero.com/oauth/RequestToken) does not work, token is null. 
Upon further investigation I noticed that the response from the previously mentioned endpoint returns a html page with the body that simply says "Sorry, something went wrong".

Based on the xero status page (https://status.xero.com/) everything works just fine so I am not sure what is the reason behind this error and was hoping that you can help me with it.

Thanks!

**Comment by ColbyLeiske** [comment]
Having the same issue. I noticed when hitting the TLS testing api route ([https://api-tls.xero.com](https://api-tls.xero.com)) I was getting back a token. Re-ran again pointing at the standard api URL, and again received no token.

The exact same code ran last week, and think it may have an issue with the TLS deprecation that took place on the 30th. 

Thanks!

**Comment by MJMortimer** [comment]
Hey @0Rudy0,
It sounds like your application is still running on a deprecated TLS version. The Xero API has been updated to require TLS 1.2.

There's some more information in #318 that should help you to update your application to work with TLS 1.2

**Comment by 0Rudy0** [comment]
That was the first thing I suspected but my project is on .net 4.6.1. and just in case I checked in fiddler which TLS version was using to send requests and it was 1.2. Additionally I tried to upgrade to newest framework 4.7.2 but it didn't help.

Even when I try to use provided MVC example in this project (which I upgraded to .net 4.6.1) I get the same error, fiddler says TLS 1.2
https://i.imgur.com/CMmmpUc.png

**Comment by MJMortimer** [comment]
Which fiddler tab are you seeing that?

I've just set up a blank solution using .Net 4.6.1 framework and still needed to force TLS 1.2 using `ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

**Comment by 0Rudy0** [comment]
I am using this "tutorial" to see which TLS version I am using:
https://stackoverflow.com/questions/34276358/how-to-test-which-version-of-tls-my-net-client-is-using

However interestingly, after I added 
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`
like you said, it works, even though in fiddler I can see version 1.2 being used with and without that part of the code. Maybe I am reading something incorrectly. 
Also I was under the impression that by targeting framework 4.6.1 and above in my project it should automatically use 1.2 version but that doesn't seem to be the case, just as in your example. Any idea why?

Thanks!

**Comment by MatthewSteeples** [comment]
@0Rudy0 Is your app running in ASP.NET? It turns out that that has a different set of defaults than console applications. We found that out the hard way too!

**Comment by MatthewSteeples** [comment]
https://stackoverflow.com/questions/43872575/net-framework-4-6-1-not-defaulting-to-tls-1-2#comment85356739_49063207 for details

**Comment by 0Rudy0** [comment]
@MatthewSteeples Ah, I see. Yes, my app is ASP.NET. Good to know, those registry settings are probably why on some server it was working and on another it wasn't.
Thanks for your help!

**Comment by MJMortimer** [comment]
It seems the issue here has been resolved so I'm gonna close this issue. Please reopen if this isn't the case
