### ISSUE TITLE
Token_rejected  with Private Authentication.

### ISSUE THREAD

**Issue by kgreed** [XeroAPI/Xero-Net#33]
It seems to me the current version has not been tested with private authentication.
This is because I had to make the changes that Jim suggests 
https://community.xero.com/developer/discussion/6639946#answer7836808   
including changing Public.Core to become Private.Core

After making these changes I progressed further, however I am now receiving a Token_rejected error
however I doing think it a fault with the actual token access because I can authenticate using an old test application that I have.

However I simply cant get this code working with private authentication.  

I have tried the suggestion at https://github.com/XeroAPI/Xero-Net/issues/31  but it hasn't helped me.

I am using .Net framework 4.5

I think whether the problem has to do with the api.UserAgent property which gets set in the code to "Xero Api - Listing example"   , which doesn't seem appropriate for private authentication

**Comment by Vikram-Shah** [comment]
private authentication not working for me as well... already wasted some time on that ..stuck at this point as exception is always thrown..
if (oauthSession is XeroApiPrivateSession)
            {
                throw new ApplicationException("The current private session cannot access the authorised organisation. Has the access token been revoked?");
            }

**Comment by ronanq** [comment]
We have made a number of changes to the wrapper and have ensured that it works for all authentication flavours. If you are still having issues with the latest version, please [let us know](https://community.xero.com/developer/topic/16971/) - our preferred support channel for general questions is our forum. 

@Vikram-Shah - your is a data one as documented here, and not an issue with the wrapper itself: http://developer.xero.com/documentation/getting-started/oauth-issues/#title1
