### ISSUE TITLE
Exception when trying to get Contacts

### ISSUE THREAD

**Issue by asmtnez** [XeroAPI/Xero-Net#330]
Hi, 
When my code execute the following :
  Xero.Api.Core.Model.Contact customer = private_app_api.Contacts.Where("AccountNumber==\"" + customerNumber + "\"").Find().FirstOrDefault();

It give me the following exception:
{"Value cannot be null.\r\nParameter name: source"}

This is happening from one or two days ago, I havent changed my code.
Thanks in advance 
Alejandro Soto

**Comment by MJMortimer** [comment]
Hey @asmtnez,

Do you have a stack trace you could provide for where the exception is happening. 

Also, if your application has only recently started to fail, then it's likely your application is still running on a deprecated TLS version. The Xero API has been updated to require TLS 1.2.

There's some more information in #318 that should help you to update your application to work with TLS 1.2

**Comment by MJMortimer** [comment]
@asmtnez Are you still having this issue?

**Comment by MJMortimer** [comment]
I'm going to close this due to lack of discussion. If this problem persists, feel free to reopen
