### ISSUE TITLE
ApiException (Code 304)

### ISSUE THREAD

**Issue by Tankzor** [XeroAPI/Xero-Net#331]
As of yesterday I'm getting ApiExceptions for some calls with status code 304 Not Modified and no message (empty body).

I can't find any change logs or anything that state this is now a valid response. Perhaps you guys know more? Should the SDK be handling this response code and returning empty/default responses instead of throwing?

I also asked here: https://community.xero.com/developer/discussion/80749621/

**Comment by Tankzor** [comment]
So I read a comment from @MJMortimer in another issue about recent issues likely being TLS1.2 change.. and yep, it was that. Weird manifestation, where'd that response code come from!

**Comment by MJMortimer** [comment]
Yeah, sorry about that. It looks like the TLS enforcement isn't playing nicely in some cases like this. I've brought it up with the appropriate team.

Thank you for bringing this to my attention. It's much appreciated
