### ISSUE TITLE
PUT not supported

### ISSUE THREAD

**Issue by Anonimex** [XeroAPI/Xero-Net#332]
I am receiving an error that PUT is not supported, when I use Invoices.Create().

It looks like people here are having the same issue: https://community.xero.com/developer/discussion/80668606/

The solution appears to be to change PUT to POST. How do I do that with this library?

**Comment by MJMortimer** [comment]
Hey @Anonimex,

The roll out of the Xero API upgrade to require TLS 1.2 is having some side effects when trying to present developers with the error that they are not using TLS 1.2+

I'm fairly certain you're running into one of these issues. Have you upgraded your integration to use TLS 1.2?

**Comment by Munies** [comment]
Hey @MJMortimer ,

I am using console application how can i upgrade TLS 1.2

**Comment by MJMortimer** [comment]
Hey @Anonimex and @Munies, are you still having an issue here?

**Comment by Anonimex** [comment]
@MJMortimer I finally worked it out. First I tried updating to .NET 4.6.1, which didn't fix it. I needed to add         Net.ServicePointManager.SecurityProtocol = Net.SecurityProtocolType.Tls12, and then it started working.
