### ISSUE TITLE
Send invoice email

### ISSUE THREAD

**Issue by AndyFelton** [XeroAPI/Xero-Net#336]
Hi,

Is it possible to send an invoice email via the API using the beta functionality as described on https://developer.xero.com/documentation/api/invoices#email. IE a post to POST https://api.xero.com/api.xro/2.0/Invoices/aa682059-c8ec-44b9-bc7f-344c94e1ffae/Email.

Thanks
Andy

**Comment by MJMortimer** [comment]
Hey @AndyFelton,

Yep you should be able to do the following once you've initialised an 'api' object.

`api.Invoices.EmailInvoice(InvoiceId)`

You can find the method signature [on the InvoicesEndpoint](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Core/Endpoints/InvoicesEndpoint.cs#L23)

One thing to note is that the return type is void, as the API returns a NoContent response. If the request fails you'll receive one of the different exceptions that the SDK throws.

**Comment by ABTanjir** [comment]
https://developer.xero.com/documentation/api/invoices#email
This part is not working, 
I'm using this code to trigger the email for an invoice,

$send_email = $this->XeroOAuth->request('POST', $this->XeroOAuth->url('Invoices/75353c1c-fe5d-430b-8305-cfda486d122c/Email', 'core'), '', '');

but it responding error:  401
