### ISSUE TITLE
Cannot update invoice after it is approved 

### ISSUE THREAD

**Issue by ManvirDynamic** [XeroAPI/Xero-Net#339]
Hello,

I am not able to update the invoice from Xero.API.SDK.Minimal package when invoice is approved. We can edit the approved invoice from Xero app. We are now using version 2.2.1.1, which we have started using recently. We believe this was working previously before upgrading to 2.2.1.1. Can you please confirm if this is problem with wrapper library.

Thanks

**Comment by MJMortimer** [comment]
Hey @ManvirDynamic,

Are you receiving some validation exceptions when this fails for you? If so, what are they?

**Comment by ManvirDynamic** [comment]
Yes, we were receiving exception as we were not setting the invoice status to approved in api while updating invoice for the approved invoice in Xero. This was wrongly done in our code. I really apologize for this.

Thanks
Manvir

**Comment by MJMortimer** [comment]
No worries @ManvirDynamic, glad to hear you've found your root cause.
