### ISSUE TITLE
Reports endpoint not deserialising JSON attributes

### ISSUE THREAD

**Issue by SamFernandoAU** [XeroAPI/Xero-Net#341]
Hello,

I've executed the "Bank Statement" report via the API previewer which gives me additional info via attributes but when the same is done via the wrapper, the attributes aren't deserialised. Appreciate if this can be looked into.

Thanks.

**Comment by SamFernandoAU** [comment]
Hey @MJMortimer  - yep, fiddler shows the response which is similar to the response I see in API Previewer.

**Comment by SamFernandoAU** [comment]
Any update on the above @MJMortimer ?

**Comment by MJMortimer** [comment]
@SamFernandoAU From what I can see the attributes are deserialized correctly.

For example:
![reportattributes](https://user-images.githubusercontent.com/5070575/44638991-9e2f5900-aa0d-11e8-9f0f-a42ba363e631.png)

Are you perhaps looking for the attributes in the wrong part of the object tree?

**Comment by SamFernandoAU** [comment]
@MJMortimer thank you - found them, was looking at the wrong level.
