### ISSUE TITLE
I can't include online my pdf 

### ISSUE THREAD

**Issue by Ema94** [XeroAPI/Xero-Net#342]
Hi.
When I put includeOnline = true in the method "Attachments. AddOrReplace". The method throw "null reference exception" error.
Regards

**Comment by MJMortimer** [comment]
Hey @Ema94, is this still an issue for you?

**Comment by Ema94** [comment]
en Xero.Api.Common.Extensions.Add(NameValueCollection collection, String name, Nullable`1 value)
   en Xero.Api.Core.Endpoints.AttachmentsEndpoint.AddOrReplace(Attachment attachment, AttachmentEndpointType type, Guid parent, Boolean includeOnline)
   en FacturanteModel.Xero.XeroApiManager.AddInvoicePdfAttachment(String invoiceId, Int32 comprobanteId, Int32 invoiceType) en C:\Proyectos\FacturanteMVC\SRC\FacturanteMVC\FacturanteModel\Xero\XeroApiManager.cs:línea 173
   en FacturanteModel.Xero.XeroApiManager.UpdateInvoiceXero() en C:\Proyectos\FacturanteMVC\SRC\FacturanteMVC\FacturanteModel\Xero\XeroApiManager.cs:línea 88
________________________________
De: MJMortimer <notifications@github.com>
Enviado: lunes, 3 de septiembre de 2018 17:45
Para: XeroAPI/Xero-Net
Cc: Ema94; Mention
Asunto: Re: [XeroAPI/Xero-Net] I can't include online my pdf (#342)


Hey @Ema94<https://nam03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEma94&data=02%7C01%7C%7Cb366c3d086a94ab5aa1408d611de2937%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636716043196544134&sdata=tooeiTxCaQaqh%2BTdxzR9MqL6cBagNUs9Zev4eh1DGWU%3D&reserved=0>, is this still an issue for you?

**Comment by MJMortimer** [comment]
Are you able to give me an example snippet of code for how you're causing this issue? Even better would be an simple console app example in a git repo I can pull down, add my consumer details to, and run to reproduce the error

**Comment by Ema94** [comment]
https://github.com/Ema94/PdfXeroIssue
________________________________
De: MJMortimer <notifications@github.com>
Enviado: martes, 4 de septiembre de 2018 17:14
Para: XeroAPI/Xero-Net
Cc: Ema94; Mention
Asunto: Re: [XeroAPI/Xero-Net] I can't include online my pdf (#342)


Are you able to give me an example snippet of code for how you're causing this issue? Even better would be an simple console app example in a git repo I can pull down, add my consumer details to, and run to reproduce the error

**Comment by MJMortimer** [comment]
This will be resolved in #349

**Comment by MJMortimer** [comment]
This should now be resolved
