### ISSUE TITLE
Set paymentsOnly=true in xero api call for cash Journal 

### ISSUE THREAD

**Issue by VyasNirav** [XeroAPI/Xero-Net#343]
Hi,
I want to get journals on cash basis so, I try "paymentsOnly=true" parameter in query but it's not work.

It will return me "No property or field 'paymentsOnly' exists in type 'Journal'"

var tempObj = api.Journals.where("paymentsOnly=true").find();

link : https://developer.xero.com/documentation/api/journals
Thank's

**Comment by MJMortimer** [comment]
Hey @VyasNirav,

You can't set that parameter via the where clause and unfortunately it has not been implemented on the JournalsEndpoint yet. 

Would like like to add a parameter to the JournalsEndpoint [similar to the offset one](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Core/Endpoints/JournalsEndpoint.cs#L21-L25)?

**Comment by VyasNirav** [comment]
Hey @MJMortimer ,

Thank you for reply.

Yes, Actually I want journals on a cash basis and for that I read the api document in Journal section it will suggest me that just set **PaymentOnly** parameter with **true** then it will return only cash basis journals

"**Would like like to add a parameter to the JournalsEndpoint similar to the offset one**?"
Yes or similar solution please.

Thank's

**Comment by MJMortimer** [comment]
@VyasNirav would you be comfortable adding the functionality in a pull request?

**Comment by VyasNirav** [comment]
Hey @MJMortimer ,

I pull request for this changes.

**Comment by MJMortimer** [comment]
The functionality has been merged in PR #346. Thanks @VyasNirav

**Comment by VyasNirav** [comment]
Thank's @MJMortimer
