### ISSUE TITLE
Consistency of Naming LineItems across Core Models

### ISSUE THREAD

**Issue by gagegreg** [XeroAPI/Xero-Net#35]
I noticed a naming consistency issue for how LineItems are called.  

The <b>Receipt</b>, <b>BankTransaction</b>, <b>CreditNote</b>, <b>RepeatingInvoice</b> all have the LineItems lists called LineItems: 

``` 
public List<LineItem> LineItems { get; set; }
```

While the <b>Invoice</b> Class is called Items:

``` 
public List<LineItem> Items { get; set; }
```

I suggest we change Invoice LineItem list to be LineItems as well in order to be consistent across classes.

**Comment by MJMortimer** [comment]
This will be addressed in #82
