### ISSUE TITLE
Issue connecting to Xero from api

### ISSUE THREAD

**Issue by Parjinder** [XeroAPI/Xero-Net#351]
Hi Xero Team,

I am getting following error when connecting to xero through api:

**An unexpected HTTP response was returned while performing OAuth operations**

Please help!

**Comment by MJMortimer** [comment]
Hey @parjinder,

Have you been able to use a tool like Fiddler to inspect the http traffic? If so, can you please provide an example of the http response? 

Cheers, 
Matt

**Comment by Parjinder** [comment]
Hi @MJMortimer 

I was able to connect to Xero through api.Issue is related to TLS updates.Xero is now using TLS 1.2  i think.

**Comment by MatthewSteeples** [comment]
Hi @Parjinder 

See https://github.com/XeroAPI/Xero-Net/issues/318 for details on how to enable TLS 1.2 for your app.

Regards,
Matthew

**Comment by Parjinder** [comment]
Thanks @MatthewSteeples
