### ISSUE TITLE
Unable to update lineitem amount on invoice

### ISSUE THREAD

**Issue by crazyhor77** [XeroAPI/Xero-Net#352]
Having trouble updating the lineitem amount on an invoice.  It works through the xero api previewer, but when i try to achieve the same task through the xero-net wrapper i get a validation exception.

```
<Invoices>
  <Invoice>
    <InvoiceID>bc9fec4d-1376-46f7-9ec3-e838c2003154</InvoiceID>
    <LineItems>
      <LineItem>
        <LineItemID>fe7eb8a9-bf7b-4951-b5ff-c44163decaff</LineItemID>
        <UnitAmount>10</UnitAmount>
        <AccountCode>230</AccountCode>
      </LineItem>
    </LineItems>
  </Invoice>
</Invoices>
```

```
            Xero.Api.Core.Model.Invoice invoice = new Xero.Api.Core.Model.Invoice()
            {
                Id = Guid.Parse("bc9fec4d-1376-46f7-9ec3-e838c2003154"),
                LineItems = new List<Xero.Api.Core.Model.LineItem>() {
                    new Xero.Api.Core.Model.LineItem()
                    {
                        LineItemId = Guid.Parse("fe7eb8a9-bf7b-4951-b5ff-c44163decaff"),
                        UnitAmount = 10,
                        AccountCode = "230"
                    }
                }
            };

            private_app_api.Invoices.Update(invoice);

```

**Comment by MJMortimer** [comment]
Hey @crazyhor77,

Have you captured the validation exception so you can see what error you're running into?

**Comment by crazyhor77** [comment]
Yeah, it says the invoice id was not found.  Bit confused as the previewer works with that same id.

**Comment by MJMortimer** [comment]
Have you confirmed that you're working with the same organisation? You can check by calling the organisations endpoint on both the preview and your application using this SDK

**Comment by crazyhor77** [comment]
Good thought, but yeah, its the same.

**Comment by crazyhor77** [comment]
Interestingly if I try to change something else on the invoice, like the InvoiceStatus, it works fine.  It only seems to be when I am updating the lineitem amount.  The invoice is still in draft status when I try to update the lineitem.

**Comment by crazyhor77** [comment]
Ok, I've found a workaround which will do the job, but I would hope the wrapper gets updated to function the same as the previewer in the future.

If I retreive the invoice using the InvoiceID first, then update the lineitems, I can successfully call an Update.  Not sure which property is required that is missing, but it will do for my purposes.  Example code below.

```
                Xero.Api.Core.Model.Invoice inv = private_app_api.Invoices.Find("931b2b14-944b-4812-8224-5dc5456d3d7a");
                inv.LineItems = new List<Xero.Api.Core.Model.LineItem>() {
                    new Xero.Api.Core.Model.LineItem()
                    {
                        LineItemId = Guid.Parse("27b15470-832f-4324-b15e-6de230e015c9"),
                        LineAmount = 50,
                        AccountCode = "230"
                    }
                };

                private_app_api.Invoices.Update(inv);
```
