### ISSUE TITLE
All Payment Ids are empty if one payment fails

### ISSUE THREAD

**Issue by crazyhor77** [XeroAPI/Xero-Net#354]
When sending a batch of payments, if one payment fails, all payment Ids are empty.  Only failed payments should have an empty Id.

**Comment by agrath** [comment]
Hi @MJMortimer 

I'm investigating an issue on one of our projects that appears to be similar in nature to this issue. 

I can raise a new issue if it's different but we are using xero.Api.Invoices.SummarizeErrors(false).Create and pushing a batch of 50 invoices. 
I'm getting a managed ValidationException thrown by the api wrapper, with 11 validation errors contained inside. 
This inherits from BadRequest, so it looks like the detail on 'Creating many resources' doesn't always apply.  (my specific error is "invoice # already exists" for 11/50 in the batch)
If the managed exception was not thrown, then I'd be able to check the ValidationStatus on the returned object(s) from .Create and handle each independently however as it is, I can't get the context of which of the 50 in the batch threw the error and handle them correctly. 
Any thoughts here?

**Comment by MJMortimer** [comment]
Hey @agrath, is this still a problem for you?

**Comment by agrath** [comment]
@MJMortimer we switched to the new API https://github.com/XeroAPI/Xero-NetStandard/ for this project however the reported issue was never resolved

**Comment by SidneyAllen** [comment]
@agrath - summarizeErrors boolean was added to createPayments in version 2.2.0

https://github.com/XeroAPI/Xero-NetStandard/releases/tag/v2.2.0

**Comment by agrath** [comment]
@SidneyAllen just to clarify, the issue was reported for the other library (not NetStandard)
We switched to the NetStandard library as part of a wider project to implement OAuth 2.0 but encountered the issue with the Xero-Net library and as far as I know it was never fixed.
