### ISSUE TITLE
How to create new Quote from Xero API

### ISSUE THREAD

**Issue by aajmot** [XeroAPI/Xero-Net#357]
Hi,
I am using this API and trying to find out which method/action needs to create new Quote using this SDK.

**Comment by MJMortimer** [comment]
Hey @aajmot. 
The API itself doesn't offer Quotes and so the SDKs cannot either. The feature itself is currently under review, and you can follow activity around it on the [UserVoice page for the feature](https://xero.uservoice.com/forums/5528-xero-accounting-api/suggestions/7040008-quotes-via-the-api)

**Comment by aajmot** [comment]
Thanks for your valuable response and the link also 👍
