### ISSUE TITLE
Method not found exception after version upgrade

### ISSUE THREAD

**Issue by vinhalo** [XeroAPI/Xero-Net#360]
We have just updated the API from v2.2.1.4 to v2.2.7.

When we are trying to call the Profit & Loss endpoint, we are now getting this exception:

Method not found: 'Xero.Api.Core.Model.Reports.Report Xero.Api.Core.Endpoints.IReportsEndpoint.ProfitAndLoss(System.Nullable`1<System.DateTime>, System.Nullable`1<System.DateTime>, System.Nullable`1<System.DateTime>, System.Nullable`1<System.Guid>, System.Nullable`1<System.Guid>, System.Nullable`1<System.Guid>, System.Nullable`1<System.Guid>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.String, System.Nullable`1<Int32>)'.

The solution builds ok, and we have not made any changes to the source code.

**Comment by MJMortimer** [comment]
The method on the ReportsEndpoint has definitely had some additions since v2.2.1.4.

v2.2.1.4: https://github.com/XeroAPI/Xero-Net/blob/v2.2.1.4/Xero.Api/Core/Endpoints/ReportsEndpoint.cs#L28-L30

vs

v2.2.7: https://github.com/XeroAPI/Xero-Net/blob/v2.2.7/Xero.Api/Core/Endpoints/ReportsEndpoint.cs#L28-L30

Are you able to confirm that your method call matches the latest method signature?

**Comment by vinhalo** [comment]
Ah thanks I didn't notice the change as it still compiled but I presume that is because of the optional arguments.

I'll check now.

**Comment by vinhalo** [comment]
I've looked at the Endpoints and it just looks like an extra 3 optional parameters have been added:

bool? paymentsOnly = null,
string timeframe = null,
int? periods = null)

As they have default values I would expect the call to still work, with these parameters given default values.  I have tried supplying all the values when calling the function as well and I am receiving the same issue.

I can see someone else has raised the same issue in the developer forums back in August, perhaps the solution has already been found?

https://community.xero.com/developer/discussion/84522003

Thanks

**Comment by MJMortimer** [comment]
It seems like at compile time your application knows about the updated SDK reference, yet at runtime cannot find the updated method in the SDK DLL being used.

Have you checked to ensure that at runtime the correct, updated DLL is being used by your running application?

You can also use a tool like [ILSpy](https://github.com/icsharpcode/ILSpy#ilspy-------) to decompile the DLL to see what version it is and what method signature exists for the method you're trying to call at runtime.

**Comment by MJMortimer** [comment]
You may also find some good information in [this stackoverflow thread/comment](https://stackoverflow.com/a/43118009/4878992)

**Comment by vinhalo** [comment]
Thanks this seems to be the cause of the problem!

Looks like maybe there's an issue with the Nuget config for the packages.  I cleared out all the previous versions of the API SDK and installed v 2.2.7 (via Nuget), and strangely it downloaded versions 2.1.10.1, 2.2.1.4 and 2.2.7 to my local nuget directory.  Visual studio then only copies v2.1.10.1 and 2.2.1.4 to my solution's packages directory, and finally copies the DLL from v 2.2.1.4 to the debug folder...

Manually copying over the v2.2.7 libraries to the debug folder seems to fix the issue.  I'm not a Nuget expert, so I'm not sure whether it's Nuget or Visual Studio or both that's caused this sequence of event.

Cheers

**Comment by vinhalo** [comment]
I think I've sorted this issue out now, thanks for your help!
