### ISSUE TITLE
Timeouts

### ISSUE THREAD

**Issue by AndyFelton** [XeroAPI/Xero-Net#362]
Hi,

I frequently seeing an issue when doing a` xeroApi.Invoices.Find(XeroId)` whereby I do not receive a response from the XERO API and get a timeout. After this all future requests will fail until I restart the application. Has this been seen before?

As I'm only getting an individual Invoice is there an alternative method?

Any help that can be provided will be appreciated.

Thanks
Andy

**Comment by jmercha** [comment]
+ 1 

We also started experiencing timeouts with the Invoices beginning November.

**Comment by MatthewSteeples** [comment]
How big are the batches that you're sending through (in terms of transaction numbers). Can you also find out how many line items you're sending through in a batch?

**Comment by BIProfessional** [comment]
I am constantly experiencing timeouts with azure data factory xero connector. 

It’s unusable with ADF because of these timeouts so I think this is not an uncommon issue.

**Comment by BIProfessional** [comment]
Is there an exact ‘how to guide’ to build this connector in visual studio ? 

I  am not experienced at building connectors and therefore even with the source code I am unsure on the steps to take to get a working connector in visual studio. 

I merely want to pull data from Xero into a SQL azure database.

Please advise

**Comment by MJMortimer** [comment]
Hi everyone, is there still an ongoing issue for anyone?

**Comment by MJMortimer** [comment]
Closing this one due to inactivity
