### ISSUE TITLE
Receive Error when Try to Run MVC App

### ISSUE THREAD

**Issue by QueenBee61** [XeroAPI/Xero-Net#363]
I receive an error in global.asax when I try to run this application.  Error is attached.

Parser Error Message: Could not load type 'Xero.Api.Example.MVC.MvcApplication'.
![image](https://user-images.githubusercontent.com/8338791/48801313-a546ca00-ecd1-11e8-9d6f-17c5e649b790.png)

**Comment by kenno23** [comment]
Hi Queebee,
Are you building in debug/release?
If you are, I ran into a similar problem and solved it by changing the build path to bin
![image](https://user-images.githubusercontent.com/9150185/48803457-189a1b80-ed66-11e8-8ab7-17f52384344b.png)
IIS will attempt to look up libraries in the bin folder. Also just to make sure, do a clean and rebuild to make sure the class is there.

**Comment by QueenBee61** [comment]
Okay, I take that back.  I had changed Inherits="Xero.Api.Example.MVC.MvcApplication" to match namespace Xero.Api.Example.MVC.  when I changed it back after changing outbput path to bin\, application made it passed the global.asax file.  Now it is throwing new errors.  Thanks for your help!

**Comment by kenno23** [comment]
No problems at all. Just remember with that change the output will be into the bin folder. 
Best of luck with your development.

**Comment by SidneyAllen** [comment]
Nice work @kenno23
