### ISSUE TITLE
Request to have assembly signed

### ISSUE THREAD

**Issue by evilanf** [XeroAPI/Xero-Net#365]
Any chance the assembly can be signed? Our project requires signing, cannot be done with the current nuget package, have to use source and rebuild.

**Comment by MJMortimer** [comment]
Hey @evilanf,

As mentioned in our readme, we won't be looking to add any new features to this SDK.

> We will continue to periodically review pull requests to fix small issues and watch for secruity issues until December 2020. Maintenance does not include adding new features, oauth 2 support or large refactoring of the code base.

Unfortunately this change will fall outside the definition of the types of changes we're looking to make.
