### ISSUE TITLE
Unable to Set UserAgent : Request GetRequestTokenAuthorizeUrl & RetrieveAndStoreAccess

### ISSUE THREAD

**Issue by manhao-chen** [XeroAPI/Xero-Net#367]
hi team,

could we have a property exposed for setting the UserAgent when calling GetRequestTokenAuthorizeUrl  and RetrieveAndStoreAccess

i see OAuthTokens.GetToken it appears to have it hard coded as

https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Infrastructure/OAuth/OAuthTokens.cs#L71

_var req = new HttpClient(baseUri)
            {
                UserAgent = "Xero Api wrapper - " + consumer.ConsumerKey
            };_

could we have it like how the HttpClient.CreateRequest does it?

_request.UserAgent = !string.IsNullOrWhiteSpace(UserAgent) ? UserAgent : "Xero Api wrapper - " + Consumer.ConsumerKey;_

cheers

**Comment by manhao-chen** [comment]
looking at the source code, it appears it is hardcoded

https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Infrastructure/OAuth/OAuthTokens.cs#L71

**Comment by MJMortimer** [comment]
Hey @manhao-chen,

As mentioned in our readme, we won't be looking to add any new features to this SDK.

> We will continue to periodically review pull requests to fix small issues and watch for secruity issues until December 2020. Maintenance does not include adding new features, oauth 2 support or large refactoring of the code base.

Unfortunately this change will fall outside the definition of the types of changes we're looking to make.
