### ISSUE TITLE
Contact.Website does not persist

### ISSUE THREAD

**Issue by softsolutionsau** [XeroAPI/Xero-Net#368]
Hey Team

I'm sending a URL in the Contact.Website field but the value does not save.

```
Contact newContact = new Contact()
                {
                    Name = "Web Dealer",
                    FirstName = "Thomas",
                    LastName = "Moore",
                    Website = "http://api.xero.com"
                };
Contact savedContact = (Contact)_xero.Create(newContact);
                Console.WriteLine(savedContact.Website); // NullException 
```

**Comment by kenno23** [comment]
Hi,

It looks like website is not available in the PUT/POST as the documentation state:
https://developer.xero.com/documentation/api/contacts

The model is probably generated from the GET , if you wish you can raise it here:
https://xero.uservoice.com/
