### ISSUE TITLE
Getting started advice

### ISSUE THREAD

**Issue by msutherland25** [XeroAPI/Xero-Net#370]
So sorry, but despite being a VB.Net developer for many years, having a paid up Xero account, having created an app connection to the sample company and got the consumer key and consumer secret, done all the SSL cert stuff etc, studied your excellent code libraries, I just can't work out how to actually run a simply test eg. get a list of contacts. All your libraries appear to be DLLs that can't be run directly. I do know how to reference other DLLs etc. Ultimately, I need to code for sending sales invoices and credit notes and purchase invoices to a Xero company via a private app. Working in C# is fairly hard for me, but I can do it, but need a simple runable example. Thank you very much for any help you can give me

**Comment by msutherland25** [comment]
OK, I have found the XeroWinForm c# example, added it to the project, made it the startup project and then ran. All compiled OK but soon gave the TLS1.0 error. It is was very unclear how to resolve this but I changed the dot net framework to 4.6 on all the projects. This then generated plenty of Nuget warnings about components installed for a different framework! Did an update on everything and still warning about NewtonSoft.Json but how do I know which dot net framework these components need anyway (can they be different, which framework should Xero.core be using?) Anyway, when I run I get an error in the Xero.Http.Client as per attached screenshot. 
![vis studio - xero test - error at designtime](https://user-images.githubusercontent.com/3532469/51630677-afd84680-1f42-11e9-9136-968ae6d789e2.PNG)
![vis studio - xero test - error](https://user-images.githubusercontent.com/3532469/51630712-c67e9d80-1f42-11e9-9983-fea3c54dd5f7.PNG)

Thank you for any help you can give. This json stuff seems rather complicated!

**Comment by kenno23** [comment]
Hi msutherland25,
That project looks like it belongs in a different repo, but for TLS for .NET 4.5 or lower you can add this line in your startup; `ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;`
You can put that in the program.cs in the main method before the main form is instantiated. 
This will allow .net 4.0 to run TLS1.2, however your environment will need .NET 4.5 installed.

**Comment by msutherland25** [comment]
Hi Kenno23, very much appreciate your response. I think I have got past the TLS issue but the example Winforms app from James Coleman which adds a contact to Xero fails with an error, so still trying to get any example to work.

**Comment by MJMortimer** [comment]
Hey @msutherland25. Is this still an issue for you?

**Comment by msutherland25** [comment]
Hi there, 

My customer decided not to go with Xero and stick with Sage sadly, so I abandoned my efforts and thus my need for a Xero API dot net library. 

Perhaps I will revisit since I use Xero myself. 

Please close the ticket. 

Regards, 

Martin 

Linkfield Data Capture Ltd 
T: +44 (0)1403 800101
