### ISSUE TITLE
Add Options to Tracking Category

### ISSUE THREAD

**Issue by jmawebtech** [XeroAPI/Xero-Net#371]
Hi,

I am trying to add options to a tracking category, but it fails. What is wrong with my code?

        /// <summary>
        /// A user can have a max of two tracking categories, but options beneath them are unlimited.
        /// </summary>
        /// <param name="trackingCategoryToCreate"></param>
        public void CreateTrackingCategory(string trackingCategoryToCreate)
        {
            TrackingCategory cat = GetCategory(trackingCategoryToCreate);

            if (cat != null)
                return;

            if (m_TrackingCategories.Count() == 0)
            {
                cat = m_Api.TrackingCategories.Create(new TrackingCategory()
                {
                    Name = trackingCategoryToCreate,
                });

                cat.Options.Add(new Option()
                {
                    Name = trackingCategoryToCreate
                });

                cat = m_Api.TrackingCategories.Update(cat);
            }
            else
            {
                m_TrackingCategories[0].Options.Add(new Option()
                {
                    Name = trackingCategoryToCreate
                });

                cat = m_Api.TrackingCategories.Update(m_TrackingCategories[0]);
            }

            m_TrackingCategories = m_Api.TrackingCategories.Find().ToList();
        }

**Comment by periander** [comment]
I'm having the same problem. Calling IOptionColleciton.Add seems to work, but returns an option with a blank GUID and it's not actually added to the TrackingCategory.

**Comment by periander** [comment]
I worked it out. I had a double space in the Option Name. Once I removed that it worked fine.

What threw me was that it seemingly worked and returned OK response but the GUID was blank. I guess that's the clue that there's something wrong.

**Comment by MJMortimer** [comment]
Hey @jmawebtech, is this still an issue for you?

**Comment by jmawebtech** [comment]
No, it's all set.
