### ISSUE TITLE
[suggestion] Invoice.Payments should be initialised to an empty collection

### ISSUE THREAD

**Issue by Tyf0x** [XeroAPI/Xero-Net#373]
Hi,

we noticed that when retrieving an invoice from the InvoicesEndpoint, the `Payments` property would be `null` if no payments are available.

Is it a reasonable request to change Xero.net to initialise the `Payments` property to an empty collection instead of `null`?

This would remove the need to check for `null` before doing any operation on the `Payments` property.

Suggested solution:
In [Invoice.cs](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Core/Model/Invoice.cs): 
```
[OnDeserialized]
public void OnDeserialized(StreamingContext context)
{
    if (Payments == null) Payments = new List<Payment>();
}
```

Thanks

**Comment by MJMortimer** [comment]
Hey @Tyf0x ,

As mentioned in our readme, we won't be looking to add any new features to this SDK.

> We will continue to periodically review pull requests to fix small issues and watch for secruity issues until December 2020. Maintenance does not include adding new features, oauth 2 support or large refactoring of the code base.

Unfortunately this change will fall outside the definition of the types of changes we're looking to make.
