### ISSUE TITLE
Get Credit Notes by CreditNoteNumber

### ISSUE THREAD

**Issue by danj1980** [XeroAPI/Xero-Net#384]
Invoices have the functionality of 
XeroAPI.Invoices.InvoiceNumbers(IEnumerable<string> invoiceNumbers)

Can you add similar functionality to Credit Notes?
IE. XeroAPI.CreditNotes.CreditNoteNumbers(IEnumerable<string> creditNoteNumbers)

**Comment by MJMortimer** [comment]
Hey @danj1980 ,

As mentioned in our readme, we won't be looking to add any new features to this SDK.

> We will continue to periodically review pull requests to fix small issues and watch for secruity issues until December 2020. Maintenance does not include adding new features, oauth 2 support or large refactoring of the code base.

Unfortunately this change will fall outside the definition of the types of changes we're looking to make.
