### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by jcrivello** [XeroAPI/Xero-Net#386]
Are there plans to release a .NET Standard 2 version of the Nuget package for this assembly? Most likely its just a matter of recompiling the assembly, and Microsoft recommends this now.

Joe

**Comment by LukeKirbyDG** [comment]
There's already a .Net standard 2 project (which is available on nuget) 
[https://github.com/XeroAPI/Xero-NetStandard](https://github.com/XeroAPI/Xero-NetStandard)

**Comment by MJMortimer** [comment]
Hey @jcrivello,

As @LukeKirbyDG has said, we've got a .NET standard version of the SDK at https://github.com/XeroAPI/Xero-NetStandard

You'll find the equivalent OAuth1.0a SDK on the `oauth1` branch. Master branch is being used for the OAuth2.0 SDK now
