### ISSUE TITLE
XeroCoreApi give Error Stream was not readable.

### ISSUE THREAD

**Issue by Sunny0989** [XeroAPI/Xero-Net#392]
**This is my code**

`var path = Path.Combine(HttpRuntime.AppDomainAppPath, "XeroCertificate/public_privatekey.pfx");`

`X509Certificate2 cert = new X509Certificate2(path, company.Password);`

` var xerocontext = new XeroCoreApi("https://api.xero.com", new PrivateAuthenticator(cert),
   new Consumer(company.ConsumerKey, company.ConsumerSecret), null);`

`return xerocontext;`

after this next statement is
`xeroContext.Contacts.Find().ToList();`

then give error **Stream was not readable.**

**Comment by LukeKirbyDG** [comment]
Have you checked to make sure the pfx is readable by the user the code is running as? 

Something like 

IO.File.Open(Path.Combine(HttpRuntime.AppDomainAppPath, "XeroCertificate/public_privatekey.pfx"), FileMode.Open, FileAccess.Read);

would throw an exception if it can't read the PFX file. It would be worth checking the stack trace of the error to see what method is actually throwing the error.

**Comment by MJMortimer** [comment]
Hi @Sunny0989,

Is this still an issue for you?

**Comment by MJMortimer** [comment]
Closing this one due to inactivity
