### ISSUE TITLE
The element 'StatusAttributeString' was not recognised.

### ISSUE THREAD

**Issue by ultimategrandson** [XeroAPI/Xero-Net#393]
This seems to relate to #257 which was closed.

> Xero.Api.Infrastructure.Exceptions.BadRequestException: The element 'StatusAttributeString' was not recognised. Ensure the element name has the correct case and that there are no duplicate elements of the same name.

I seem to get this error whenever I bulk post invoices and they succeed, it is to do with the ValidationStatus enum which should be "OK" and not "Ok". 

See also: https://community.xero.com/developer/discussion/11613135

**Comment by MJMortimer** [comment]
Hey @ultimategrandson,

From the discussion in community it looks like the issues seemed to be with users on mono, and there being overly verbose serialization when in that environment due to a bug on their side. 

What is your setup like?

**Comment by MJMortimer** [comment]
Closing this one due to inactivity
