### ISSUE TITLE
Contact.BatchPayments. Only BankAccountNumber is persisted

### ISSUE THREAD

**Issue by simonlaszcz** [XeroAPI/Xero-Net#397]
When creating a contact with BatchPaymentContactDefaults, it appears that only BankAccountNumber is persisted. 

The other properties (Details, Reference, Code, BankAccountName) are ignored.

Thanks

**Comment by MJMortimer** [comment]
I believe at this stage those properties are read only in the Xero API. You can express your interest in add new functionality to be able to set these properties by requesting the change on our [User Voice page](https://xero.uservoice.com/forums/5528-xero-accounting-api)
