### ISSUE TITLE
BatchPayments PaymentDate set incorretly.

### ISSUE THREAD

**Issue by LukeKirbyDG** [XeroAPI/Xero-Net#399]
Hi,

Ran into an issue when adding batch payments using the payment date as Date.Today in .NET and found in the response the actual date was set to yesterday. After a little investigation, the payment date passed to the API was Date at midnight <Date>2019-09-11T00:00:00+01:00</Date> but in the response it was 11pm yesterday "DateString": "2019-09-10T23:00:00. 

I've added a PR with a potential fix for it by adding an extra field for the serialized date string which formats the date field as yyyy-MM-dd when getting the value. I've added a simple unit test for creating a batch payment as I couldn't find an existing one specifically for batch payments. 

https://github.com/XeroAPI/Xero-Net/pull/398

**Comment by MJMortimer** [comment]
Added in latest merge. New version will be going out shortly
