### ISSUE TITLE
Get files from a folder by folder id

### ISSUE THREAD

**Issue by corientdev** [XeroAPI/Xero-Net#405]
Hi as per the api documentation @ https://developer.xero.com/documentation/files-api/folders

the folder returns files as well in the folder which doesn't seem to be implemented in current version of xero .net lib

**Comment by MJMortimer** [comment]
Hey @corientdev,

As mentioned in our readme, we won't be looking to add any new features to this SDK.

> We will continue to periodically review pull requests to fix small issues and watch for secruity issues until December 2020. Maintenance does not include adding new features, oauth 2 support or large refactoring of the code base.

Unfortunately this change will fall outside the definition of the types of changes we're looking to make.
