### ISSUE TITLE
Deprecated in favour of Xero-NetStandard?

### ISSUE THREAD

**Issue by Tyf0x** [XeroAPI/Xero-Net#413]
This lib hasn't been updated for a year and has dropped from the [official](https://developer.xero.com/documentation/libraries/using-the-xero-api-with-c) doc.

Has the repo been abandoned in favour of the Xero/Xero-NetStandard repo?

If it is the case, shouldn't the readme be updated to warn users and direct them to the new project home?

Thanks

**Comment by SidneyAllen** [comment]
Hi @Tyf0x 

Thanks for brining this to our attention.  I've updated the README to reflect the status of this library.
