### ISSUE TITLE
oauth_problem=consumer_key_unknown for OAuth 2.0 App

### ISSUE THREAD

**Issue by binin24x7** [XeroAPI/Xero-Net#415]
Dose this project support OAuth 2.0?
Do i need to make any changes on the sample application to solve this error,
i am using valid consumer_key from new Xero OAuth 2.0 developer App

**Comment by cdenvir** [comment]
Hi @binin24x7 I'm having the same issue, I also noticed the consumer keys and secrets are in a different format to what they were previously (which is currently working on other software we have running) so it's likely incompatible with this API now.

**Comment by MattR-Api** [comment]
Hi @binin24x7 and @cdenvir 

This Project is for our older OAuth 1.0a Authentication method, the OAuth 2.0 Project you'll be looking for can be found [here](https://github.com/XeroAPI/Xero-NetStandard).

As a side note, OAuth 2.0 no longer uses Consumer Keys and Secrets, and instead uses Client ID and Client Secrets. They are not compatible or interchangeable between the two authentication methods.

Kind Regards

Matt
