### ISSUE TITLE
Can we use this library with OAUTH 2.0 ?

### ISSUE THREAD

**Issue by redware** [XeroAPI/Xero-Net#416]
I have OAUTH 2.0 authentication working and can get an access token - but cannot see how to use this library with OAUTH 2.0 tokens.... I can see a way to migrate the old PFX files for security but what about a new application - can we still use this library in the short term and get it to authenticate by giving it an access token (I have a lot of code depending on it) ?

Thank you,

**Comment by SidneyAllen** [comment]
@redware we've post the status of this library at the top of the README
https://github.com/XeroAPI/Xero-Net/blob/master/README.md

Please look at this project for our OAuth 2 SDK
https://github.com/XeroAPI/Xero-NetStandard
