### ISSUE TITLE
PDF attached as related files not as included files. 

### ISSUE THREAD

**Issue by DKJ222425** [XeroAPI/Xero-Net#424]
I have used CreateInvoiceAttachmentByFileNameAsyncWithHttpInfo method. As a result, file is getting included as "Related Files" in the portal.

If it is in related file, users need to manually attach the files while sending emails. Attaching as included files will save me a lot of time.

Can this be made as "Included files" instead of "Related files" by invoking CreateInvoiceAttachmentByFileNameAsyncWithHttpInfo?

Thanks.

**Comment by MJMortimer** [comment]
Hey @DKJ222425,

It looks like you've raised this issue against the wrong GitHub repo. This is the repository for the deprecated OAuth1.0a SDK, whereas the functionality you're talking about is included in the OAuth2.0 SDK [located here](https://github.com/XeroAPI/Xero-NetStandard). 

Can you please reopen your issue there?

Cheers,
Matt
