### ISSUE TITLE
Unit DP 4 digits

### ISSUE THREAD

**Issue by SashaBoss** [XeroAPI/Xero-Net#425]
Is it possible to use 4 digits using your library for tax rounding as described in this article?
https://developer.xero.com/documentation/api-guides/rounding-in-xero

**Comment by MJMortimer** [comment]
Yep, on each request you can explicitly choose to enable 4dp for the endpoints that allow it. Each of the endpoints will have [this method provided from the base class](https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Core/Endpoints/Base/FourDecimalPlacesEndpoint.cs#L15) and you'd use the method the same way you would with paging/querying.
