### ISSUE TITLE
Callback support removed from example authenticators?

### ISSUE THREAD

**Issue by chappoo** [XeroAPI/Xero-Net#45]
In the latest change-sets it looks like support for callback urls has been removed.  Just wondering why this was done; are we supposed to maintain our own authenticator / signing code; as it's a core requirement to need the callback when used in the wild?

A bit of clarity around the intended consumption pattern of the wrapper would be much appreciated.

Thanks
Steve

**Comment by mjava1** [comment]
Hi Steve,

We made some changes to support callback url and there is now an MVC sample under /Xero.Api.Example.MVC - just edit XeroApiHelper.cs accordingly. Let me know how you get on.

Javed
