### ISSUE TITLE
AccountType enum needs a value for Inventory

### ISSUE THREAD

**Issue by jmoorehead** [XeroAPI/Xero-Net#52]
We have our own framework and don't consume the client api or I would just make the change and send a pull request. We noticed that recently the API will return an AccountType of INVENTORY which isn't represented in the AccountType definition.

https://github.com/XeroAPI/Xero-Net/blob/master/Xero.Api/Core/Model/Types/AccountType.cs

Cheers!

**Comment by MJMortimer** [comment]
Added in #53
