### ISSUE TITLE
NuGet Package Version

### ISSUE THREAD

**Issue by chappoo** [XeroAPI/Xero-Net#64]
Hi all,

Currently there is no way to correlate the change history in GIT with the version published to NuGet (https://www.nuget.org/packages/Xero.API.SDK/).

Would it be possible to include the GIT commit hash that was built in the package metadata somewhere? (Either that or release notes, but automation is always better...:)).  This would provide some transparency as to where the package is at.  I know it's technically possible, but I'm not sure how the package / publish process is setup; i.e. you can inject custom properties into the nuget.exe pack command.

Thanks
Steve

**Comment by MJMortimer** [comment]
This is a good suggestion. I will look into ways that we can add this to our current process of nuget deployment for the next release

**Comment by MJMortimer** [comment]
A github link will be added into the release notes in the metadata while we explore some automated options. The link will point to the tree with the up to date code for the nuget. You can see the change in the latest nugets that have just been released :)

**Comment by philals** [comment]
Hi Chappoo. We have started adding the Git hash on Nuget and will from now also create a Release tag. Thanks.
