### ISSUE TITLE
NuGet package dependency SQL Lite?

### ISSUE THREAD

**Issue by chappoo** [XeroAPI/Xero-Net#65]
Why does the Xero.API.SDK package now pull a dependency on System.Data.SQLite (and itself, another 3 dependencies) when they're not required by the core wrapper dll?  (introduced in change 1c176663151beab1beef964d4422d688bd99709b).  I've just updated to the latest package version (2.0.5) and now I'm forced to take a dependency on all these other dependencies, which are completely unnecessary to satisfy full run-time closure of our app.  I have to state an objection to this, as most of the users will not be requiring the examples.  This also slows down builds, which isn't good.

It looks like it's there because, for some reason, the package is bundled with the examples.  I'd have thought a better way of packaging this is to pack the examples into another package (Xero.API.SDK.Examples perhaps) which itself has a dependency on the Xero.API.SDK package.  Or flip-side pull the core wrapper dll into a **dependency free** package and do the opposite.  Either way, much better than forcing your customers to install packages they don't need.

Please consider doing this, it will save headaches for consumers in the future.

Regards
Steve

**Comment by chappoo** [comment]
OK, it looks like this might be a WIP towards a potential solution: https://github.com/XeroAPI/Xero-Net/blob/master/minimal.nuspec?

**Comment by rowley-xero** [comment]
Take a look at Xero.API.SDK.Minimal. This is a newer package which does not have the dependency. We've had others complain that they have to add the dependencies.

**Comment by rowley-xero** [comment]
Thanks for your input.

**Comment by rowley-xero** [comment]
Opps didn't mean to close that :(

**Comment by chappoo** [comment]
I wasn't aware of that package; thanks for letting me know.

**Comment by rowley-xero** [comment]
We created it today. We made the choice to add the missing dependencies to the existing package and create this lighter weight one. Hope it helps.

**Comment by chappoo** [comment]
Is Xero.Api.Example.Applications.dll still needed in that package?  I can remove the reference manually for now.

**Comment by rowley-xero** [comment]
Very good point. Others have found the Example.Applications useful.

**Comment by chappoo** [comment]
Agreed, great value and they certainly helped us too.  Prob handy in the main SDK package now it's split?

**Comment by MJMortimer** [comment]
The way the nugets are set up at the moment seems to be working well. If we receive any extra feedback in the future we can revisit this issue and tweak them some more.
