### ISSUE TITLE
Account Updating

### ISSUE THREAD

**Issue by RungeDev** [XeroAPI/Xero-Net#67]
Hi,
We're using the Xero API to sync account data but currently only the Status of an account can be updated. Do you have a timescale for when more fields will become available for update via the API? 
Thanks

**Comment by MJMortimer** [comment]
The functionality to do this has recently been released by Xero. I am adding the functionality to the wrapper now :)

**Comment by MJMortimer** [comment]
The functionality is now in the wrapper
