### ISSUE TITLE
Quote & Purchase orders via API

### ISSUE THREAD

**Issue by RungeDev** [XeroAPI/Xero-Net#68]
Hi,
What is the latest news on Quotes and purchase orders via the API? Is there a timeframe for them to be up and running?
Thanks

**Comment by MJMortimer** [comment]
This functionality is not yet available via Xero's API and so it can't be added to the wrapper. 
There is currently no timeframe for them yet, but you can keep up to date with these using our uservoice. 

Quotes: https://xero.uservoice.com/forums/5528-xero-core-api/suggestions/7040008-quotes-via-the-api 

Purchase orders: https://xero.uservoice.com/forums/5528-xero-core-api/suggestions/4327134-enable-the-upcoming-purchase-order-module-to-link
