### ISSUE TITLE
Partner App Token Renewal examples

### ISSUE THREAD

**Issue by RileyJamesXero** [XeroAPI/Xero-Net#72]
The wrapper now supports Partner App's & Token Renewal based on this PR (https://github.com/XeroAPI/Xero-Net/pull/38).

Could the documentation be updated to reflect these changes?
https://github.com/XeroAPI/Xero-Net#partnerauthenticator

An example of how to use the token renewal functions would be a bonus

**Comment by MJMortimer** [comment]
Readme has been altered to say that token renewal is provided. Examples are a little tricky to give because it spans across a few classes. I have instead noted the initial classes and methods that kick off the process so users can start and follow from there

**Comment by MJMortimer** [comment]
@RileyJamesXero Is this still an issue? Or were the changes to the readme documentation all good?
