### ISSUE TITLE
Xero.Api.Infrastructure.Http.Response Initialization

### ISSUE THREAD

**Issue by ksasha** [XeroAPI/Xero-Net#74]
Serveral methods in Xero.Api.Infrastructure.Http.HttpClient class do create Response object in case of an exception, by casting WebExceptionResponse...

However, in some cases, Response property of WebException object is a null reference:
For instance, In case api.xero.com is not reachable, a SocketException is being thrown, and because WebException.Response is null in such case, line 
`return new Response((HttpWebResponse)we.Response);` 
throws an exception of its own (NullReferenceException) from within the constructor of Response class.

**Comment by MJMortimer** [comment]
This will be addressed in #84. The changes will check if the WebExceptions response is null before trying to wrap it up. If the response is null the exception is just thrown back up the chain to allow the client to deal with it how they see fit
