### ISSUE TITLE
BankStateBranch is an integer field - should be a string

### ISSUE THREAD

**Issue by christhecoder** [XeroAPI/Xero-Net#93]
The BankStateBranch property on a number of objects (including Employee in the Australian Payroll API) is an integer.  However, when a BSB number has a leading 0 (e.g. 012345) and  is converted to an integer, the leading 0 is dropped.  This then results in the validation error "BSB requires 6 digits" in the response.  This property should be a string instead of an integer.

As a side note, there doesn't seem to be a way to get what the validation errors are from the exception. It would be useful to have this information for logging purposes in production.  I had to identify this problem using Fiddler and inspecting the JSON response.

**Comment by tamaw** [comment]
There's an older version of the this library which has this property as a string. 2.0.4.0 (?)

**Comment by philals** [comment]
Fixed in https://github.com/XeroAPI/Xero-Net/pull/160 Thanks @tamaw
