### ISSUE TITLE
The page you are attempting to access requires an SSL client certificate

### ISSUE THREAD

**Issue by hedecan** [XeroAPI/Xero-Net#97]
Hi there,

I have made all the settings referring the partner application. I am receiving the 403 Forbidden Error at OAuthToken class at0 
if (response.StatusCode != HttpStatusCode.OK)
            {
                throw new OAuthException(response.Body);
            }

What could be the cause ? thank you

**Comment by ronanq** [comment]
For general questions and assistance, it is best to use our developer community: https://community.xero.com/developer/
